//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.25 at 12:41:06 PM IST 
//


package com.jnj.gt.aspac_epic_simulate_v1.simulatewebservice;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderLinesOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderLinesOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ITM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MATERIAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MAT_ENTRD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SHORT_TEXT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REQ_QTY" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CUM_CF_QTY" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="BASE_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SALES_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITM_CATEGRY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PLANT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBSTREASO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HG_LV_ITEM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NET_PRICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NET_VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TAX_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ROUTE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SHIP_POINT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BATCH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="REA_FOR_RE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUBTOT_PP6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PRICE_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNLOAD_POINT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manualSubLinesOutput" type="{http://www.jnj.com/aspac/processStockAndPriceRequestInput}ManualSubLinesOutput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scheduledLinesOutput" type="{http://www.jnj.com/aspac/processStockAndPriceRequestInput}ScheduledLinesOutput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="returnMessage" type="{http://www.jnj.com/aspac/processStockAndPriceRequestInput}ReturnMessage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderLinesOutput", propOrder = {
    "itmnumber",
    "material",
    "matentrd",
    "shorttext",
    "reqqty",
    "cumcfqty",
    "baseuom",
    "salesuom",
    "itmcategry",
    "plant",
    "substreaso",
    "hglvitem",
    "netprice",
    "netvalue",
    "taxamount",
    "route",
    "shippoint",
    "batch",
    "reaforre",
    "subtotpp1",
    "subtotpp2",
    "subtotpp3",
    "subtotpp4",
    "subtotpp5",
    "subtotpp6",
    "pricetype",
    "unloadpoint",
    "manualSubLinesOutput",
    "scheduledLinesOutput",
    "returnMessage"
})
public class OrderLinesOutput {

    @XmlElement(name = "ITM_NUMBER")
    protected int itmnumber;
    @XmlElement(name = "MATERIAL", required = true)
    protected String material;
    @XmlElement(name = "MAT_ENTRD", required = true)
    protected String matentrd;
    @XmlElement(name = "SHORT_TEXT", required = true)
    protected String shorttext;
    @XmlElement(name = "REQ_QTY")
    protected long reqqty;
    @XmlElement(name = "CUM_CF_QTY")
    protected long cumcfqty;
    @XmlElement(name = "BASE_UOM", required = true)
    protected String baseuom;
    @XmlElement(name = "SALES_UOM", required = true)
    protected String salesuom;
    @XmlElement(name = "ITM_CATEGRY", required = true)
    protected String itmcategry;
    @XmlElement(name = "PLANT", required = true)
    protected String plant;
    @XmlElement(name = "SUBSTREASO", required = true)
    protected String substreaso;
    @XmlElement(name = "HG_LV_ITEM")
    protected int hglvitem;
    @XmlElement(name = "NET_PRICE", required = true)
    protected String netprice;
    @XmlElement(name = "NET_VALUE", required = true)
    protected String netvalue;
    @XmlElement(name = "TAX_AMOUNT", required = true)
    protected String taxamount;
    @XmlElement(name = "ROUTE", required = true)
    protected String route;
    @XmlElement(name = "SHIP_POINT", required = true)
    protected String shippoint;
    @XmlElement(name = "BATCH", required = true)
    protected String batch;
    @XmlElement(name = "REA_FOR_RE", required = true)
    protected String reaforre;
    @XmlElement(name = "SUBTOT_PP1", required = true)
    protected String subtotpp1;
    @XmlElement(name = "SUBTOT_PP2", required = true)
    protected String subtotpp2;
    @XmlElement(name = "SUBTOT_PP3", required = true)
    protected String subtotpp3;
    @XmlElement(name = "SUBTOT_PP4", required = true)
    protected String subtotpp4;
    @XmlElement(name = "SUBTOT_PP5", required = true)
    protected String subtotpp5;
    @XmlElement(name = "SUBTOT_PP6", required = true)
    protected String subtotpp6;
    @XmlElement(name = "PRICE_TYPE", required = true)
    protected String pricetype;
    @XmlElement(name = "UNLOAD_POINT", required = true)
    protected String unloadpoint;
    protected List<ManualSubLinesOutput> manualSubLinesOutput;
    protected List<ScheduledLinesOutput> scheduledLinesOutput;
    protected List<ReturnMessage> returnMessage;

    /**
     * Gets the value of the itmnumber property.
     * 
     */
    public int getITMNUMBER() {
        return itmnumber;
    }

    /**
     * Sets the value of the itmnumber property.
     * 
     */
    public void setITMNUMBER(int value) {
        this.itmnumber = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIAL() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIAL(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the matentrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATENTRD() {
        return matentrd;
    }

    /**
     * Sets the value of the matentrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATENTRD(String value) {
        this.matentrd = value;
    }

    /**
     * Gets the value of the shorttext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHORTTEXT() {
        return shorttext;
    }

    /**
     * Sets the value of the shorttext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHORTTEXT(String value) {
        this.shorttext = value;
    }

    /**
     * Gets the value of the reqqty property.
     * 
     */
    public long getREQQTY() {
        return reqqty;
    }

    /**
     * Sets the value of the reqqty property.
     * 
     */
    public void setREQQTY(long value) {
        this.reqqty = value;
    }

    /**
     * Gets the value of the cumcfqty property.
     * 
     */
    public long getCUMCFQTY() {
        return cumcfqty;
    }

    /**
     * Sets the value of the cumcfqty property.
     * 
     */
    public void setCUMCFQTY(long value) {
        this.cumcfqty = value;
    }

    /**
     * Gets the value of the baseuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBASEUOM() {
        return baseuom;
    }

    /**
     * Sets the value of the baseuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBASEUOM(String value) {
        this.baseuom = value;
    }

    /**
     * Gets the value of the salesuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESUOM() {
        return salesuom;
    }

    /**
     * Sets the value of the salesuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESUOM(String value) {
        this.salesuom = value;
    }

    /**
     * Gets the value of the itmcategry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITMCATEGRY() {
        return itmcategry;
    }

    /**
     * Sets the value of the itmcategry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITMCATEGRY(String value) {
        this.itmcategry = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLANT() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLANT(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the substreaso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBSTREASO() {
        return substreaso;
    }

    /**
     * Sets the value of the substreaso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBSTREASO(String value) {
        this.substreaso = value;
    }

    /**
     * Gets the value of the hglvitem property.
     * 
     */
    public int getHGLVITEM() {
        return hglvitem;
    }

    /**
     * Sets the value of the hglvitem property.
     * 
     */
    public void setHGLVITEM(int value) {
        this.hglvitem = value;
    }

    /**
     * Gets the value of the netprice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETPRICE() {
        return netprice;
    }

    /**
     * Sets the value of the netprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETPRICE(String value) {
        this.netprice = value;
    }

    /**
     * Gets the value of the netvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETVALUE() {
        return netvalue;
    }

    /**
     * Sets the value of the netvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETVALUE(String value) {
        this.netvalue = value;
    }

    /**
     * Gets the value of the taxamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXAMOUNT() {
        return taxamount;
    }

    /**
     * Sets the value of the taxamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXAMOUNT(String value) {
        this.taxamount = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUTE() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUTE(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the shippoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPOINT() {
        return shippoint;
    }

    /**
     * Sets the value of the shippoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPOINT(String value) {
        this.shippoint = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBATCH() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBATCH(String value) {
        this.batch = value;
    }

    /**
     * Gets the value of the reaforre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREAFORRE() {
        return reaforre;
    }

    /**
     * Sets the value of the reaforre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREAFORRE(String value) {
        this.reaforre = value;
    }

    /**
     * Gets the value of the subtotpp1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP1() {
        return subtotpp1;
    }

    /**
     * Sets the value of the subtotpp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP1(String value) {
        this.subtotpp1 = value;
    }

    /**
     * Gets the value of the subtotpp2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP2() {
        return subtotpp2;
    }

    /**
     * Sets the value of the subtotpp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP2(String value) {
        this.subtotpp2 = value;
    }

    /**
     * Gets the value of the subtotpp3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP3() {
        return subtotpp3;
    }

    /**
     * Sets the value of the subtotpp3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP3(String value) {
        this.subtotpp3 = value;
    }

    /**
     * Gets the value of the subtotpp4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP4() {
        return subtotpp4;
    }

    /**
     * Sets the value of the subtotpp4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP4(String value) {
        this.subtotpp4 = value;
    }

    /**
     * Gets the value of the subtotpp5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP5() {
        return subtotpp5;
    }

    /**
     * Sets the value of the subtotpp5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP5(String value) {
        this.subtotpp5 = value;
    }

    /**
     * Gets the value of the subtotpp6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBTOTPP6() {
        return subtotpp6;
    }

    /**
     * Sets the value of the subtotpp6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBTOTPP6(String value) {
        this.subtotpp6 = value;
    }

    /**
     * Gets the value of the pricetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRICETYPE() {
        return pricetype;
    }

    /**
     * Sets the value of the pricetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRICETYPE(String value) {
        this.pricetype = value;
    }

    /**
     * Gets the value of the unloadpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNLOADPOINT() {
        return unloadpoint;
    }

    /**
     * Sets the value of the unloadpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNLOADPOINT(String value) {
        this.unloadpoint = value;
    }

    /**
     * Gets the value of the manualSubLinesOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manualSubLinesOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManualSubLinesOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManualSubLinesOutput }
     * 
     * 
     */
    public List<ManualSubLinesOutput> getManualSubLinesOutput() {
        if (manualSubLinesOutput == null) {
            manualSubLinesOutput = new ArrayList<ManualSubLinesOutput>();
        }
        return this.manualSubLinesOutput;
    }

    /**
     * Gets the value of the scheduledLinesOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledLinesOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledLinesOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduledLinesOutput }
     * 
     * 
     */
    public List<ScheduledLinesOutput> getScheduledLinesOutput() {
        if (scheduledLinesOutput == null) {
            scheduledLinesOutput = new ArrayList<ScheduledLinesOutput>();
        }
        return this.scheduledLinesOutput;
    }

    /**
     * Gets the value of the returnMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnMessage }
     * 
     * 
     */
    public List<ReturnMessage> getReturnMessage() {
        if (returnMessage == null) {
            returnMessage = new ArrayList<ReturnMessage>();
        }
        return this.returnMessage;
    }

}
