//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.25 at 12:41:06 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.jnj.com/aspac/processStockAndPriceRequestInput", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jnj.gt.aspac_epic_simulate_v1.simulatewebservice;
