//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.25 at 12:41:06 PM IST 
//


package com.jnj.gt.aspac_epic_simulate_v1.simulatewebservice;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestBackOrderItemFromGatewayInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestBackOrderItemFromGatewayInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in_OrderType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="in_ShipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="in_BillTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="in_AccountCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderLinesInput" type="{http://www.jnj.com/aspac/processStockAndPriceRequestInput}OrderLinesInput" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestBackOrderItemFromGatewayInput", propOrder = {
    "inOrderType",
    "inShipTo",
    "inBillTo",
    "inAccountCountry",
    "orderLinesInput"
})
public class TestBackOrderItemFromGatewayInput {

    @XmlElement(name = "in_OrderType", required = true)
    protected String inOrderType;
    @XmlElement(name = "in_ShipTo", required = true)
    protected String inShipTo;
    @XmlElement(name = "in_BillTo", required = true)
    protected String inBillTo;
    @XmlElement(name = "in_AccountCountry", required = true)
    protected String inAccountCountry;
    @XmlElement(required = true)
    protected List<OrderLinesInput> orderLinesInput;

    /**
     * Gets the value of the inOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInOrderType() {
        return inOrderType;
    }

    /**
     * Sets the value of the inOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInOrderType(String value) {
        this.inOrderType = value;
    }

    /**
     * Gets the value of the inShipTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInShipTo() {
        return inShipTo;
    }

    /**
     * Sets the value of the inShipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInShipTo(String value) {
        this.inShipTo = value;
    }

    /**
     * Gets the value of the inBillTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBillTo() {
        return inBillTo;
    }

    /**
     * Sets the value of the inBillTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBillTo(String value) {
        this.inBillTo = value;
    }

    /**
     * Gets the value of the inAccountCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInAccountCountry() {
        return inAccountCountry;
    }

    /**
     * Sets the value of the inAccountCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInAccountCountry(String value) {
        this.inAccountCountry = value;
    }

    /**
     * Gets the value of the orderLinesInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLinesInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLinesInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLinesInput }
     * 
     * 
     */
    public List<OrderLinesInput> getOrderLinesInput() {
        if (orderLinesInput == null) {
            orderLinesInput = new ArrayList<OrderLinesInput>();
        }
        return this.orderLinesInput;
    }

}
