//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 12:46:33 PM IST 
//


package com.jnj.hcswmd01.mu007_epic_ordercreate_v1.ordercreationinsapwebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jnj.hcswmd01.mu007_epic_ordercreate_v1.ordercreationinsapwebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderCreationInSAPInput_QNAME = new QName("http://hcswmd01.jnj.com/MU007_EPIC_OrderCreate_v1/orderCreationInSAPWebservice", "orderCreationInSAPInput");
    private final static QName _OrderCreationInSAPOutput_QNAME = new QName("http://hcswmd01.jnj.com/MU007_EPIC_OrderCreate_v1/orderCreationInSAPWebservice", "orderCreationInSAPOutput");
    private final static QName _OutOrderLinesDiscounts_QNAME = new QName("", "Discounts");
    private final static QName _OutOrderLinesShippingPoint_QNAME = new QName("", "ShippingPoint");
    private final static QName _OutOrderLinesFeeMin_QNAME = new QName("", "FeeMin");
    private final static QName _OutOrderLinesMaterialEntered_QNAME = new QName("", "MaterialEntered");
    private final static QName _OutOrderLinesGrossPrice_QNAME = new QName("", "GrossPrice");
    private final static QName _OutOrderLinesFreight_QNAME = new QName("", "Freight");
    private final static QName _OutOrderLinesMessage_QNAME = new QName("", "Message");
    private final static QName _OutOrderLinesFee_QNAME = new QName("", "Fee");
    private final static QName _OutOrderLinesHandling_QNAME = new QName("", "Handling");
    private final static QName _OutOrderLinesBillingDeliveryBlock_QNAME = new QName("", "BillingDeliveryBlock");
    private final static QName _OutOrderLinesTax_QNAME = new QName("", "Tax");
    private final static QName _OutOrderLinesFreightAndHandling_QNAME = new QName("", "FreightAndHandling");
    private final static QName _OutOrderLinesHSAPromotion_QNAME = new QName("", "HSAPromotion");
    private final static QName _OutOrderLinesDropShipFee_QNAME = new QName("", "DropShipFee");
    private final static QName _OutOrderLinesLineNumber_QNAME = new QName("", "LineNumber");
    private final static QName _OutOrderLinesBaseUOM_QNAME = new QName("", "BaseUOM");
    private final static QName _OutOrderLinesPriceType_QNAME = new QName("", "PriceType");
    private final static QName _OutOrderLinesNetValue_QNAME = new QName("", "NetValue");
    private final static QName _OutOrderLinesSubstitutionReason_QNAME = new QName("", "SubstitutionReason");
    private final static QName _OutOrderLinesMaterialNumber_QNAME = new QName("", "MaterialNumber");
    private final static QName _OutOrderLinesSalesUOM_QNAME = new QName("", "SalesUOM");
    private final static QName _OutOrderLinesItemCategory_QNAME = new QName("", "ItemCategory");
    private final static QName _OutOrderLinesHigherLevelItemNumber_QNAME = new QName("", "HigherLevelItemNumber");
    private final static QName _OutOrderLinesRoute_QNAME = new QName("", "Route");
    private final static QName _OutOrderLinesAvailableQuantity_QNAME = new QName("", "AvailableQuantity");
    private final static QName _OrderCreationInSAPOutputErrorMessage_QNAME = new QName("", "errorMessage");
    private final static QName _OrderCreationInSAPInputInGatewayRelatedOrdernumber_QNAME = new QName("", "in_GatewayRelatedOrdernumber");
    private final static QName _OrderCreationInSAPInputInHouseAccount_QNAME = new QName("", "in_HouseAccount");
    private final static QName _OrderCreationInSAPInputInCreditCardAccountNumber_QNAME = new QName("", "in_CreditCardAccountNumber");
    private final static QName _OrderCreationInSAPInputInCustomerNotes_QNAME = new QName("", "in_CustomerNotes");
    private final static QName _OrderCreationInSAPInputInDealerPONumber_QNAME = new QName("", "in_DealerPONumber");
    private final static QName _OrderCreationInSAPInputInOrderReason_QNAME = new QName("", "in_OrderReason");
    private final static QName _OrderCreationInSAPInputInRequestedDeliveryDate_QNAME = new QName("", "in_RequestedDeliveryDate");
    private final static QName _OrderCreationInSAPInputInCreditCardExpirationCard_QNAME = new QName("", "in_CreditCardExpirationCard");
    private final static QName _OrderCreationInSAPInputInCreditCardType_QNAME = new QName("", "in_CreditCardType");
    private final static QName _OrderCreationInSAPInputInCreditCardSequenceNumber_QNAME = new QName("", "in_CreditCardSequenceNumber");
    private final static QName _OrderCreationInSAPInputInHoldCode_QNAME = new QName("", "in_HoldCode");
    private final static QName _OrderCreationInSAPInputInBillToNumber_QNAME = new QName("", "in_BillToNumber");
    
    private final static QName _OrderCreationInSAPInputInAddressName_QNAME = new QName("", "in_AddressName");
    private final static QName _OrderCreationInSAPInputInAddressStreet_QNAME = new QName("", "in_AddressStreet");
    private final static QName _OrderCreationInSAPInputInAddressStrSuppl1r_QNAME = new QName("", "in_AddressStr_Suppl1");
    private final static QName _OrderCreationInSAPInputInAddressCity_QNAME = new QName("", "in_AddressCity");
    private final static QName _OrderCreationInSAPInputInAddressRegion_QNAME = new QName("", "in_AddressRegion");
    private final static QName _OrderCreationInSAPInputInAddressPostlCod1QNAME = new QName("", "in_AddressPostl_Cod1");
    private final static QName _OrderCreationInSAPInputInAddressCountry_QNAME = new QName("", "in_AddressCountry");
    
    private final static QName _InOrderTextTEXTID_QNAME = new QName("", "TEXT_ID");
    private final static QName _InOrderTextTEXTLINE_QNAME = new QName("", "TEXT_LINE");
    
    private final static QName _InOrderLinesPlant_QNAME = new QName("", "Plant");
    private final static QName _InOrderLinesLot_QNAME = new QName("", "Lot");
    private final static QName _InOrderLinesUnloadingPoint_QNAME = new QName("", "UnloadingPoint");
    private final static QName _InOrderLinesCustomerLineNumber_QNAME = new QName("", "CustomerLineNumber");
    private final static QName _ScheduledLinesScheduledLineNumber_QNAME = new QName("", "ScheduledLineNumber");
    private final static QName _ScheduledLinesDeliveryDate_QNAME = new QName("", "DeliveryDate");
    private final static QName _ScheduledLinesQuantity_QNAME = new QName("", "quantity");
    private final static QName _ScheduledLinesShipDate_QNAME = new QName("", "ShipDate");
    private final static QName _ScheduledLinesLineStatus_QNAME = new QName("", "LineStatus");
    private final static QName _ScheduledLinesMaterialAvailabilityDate_QNAME = new QName("", "MaterialAvailabilityDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jnj.hcswmd01.mu007_epic_ordercreate_v1.ordercreationinsapwebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderCreationInSAPOutput }
     * 
     */
    public OrderCreationInSAPOutput createOrderCreationInSAPOutput() {
        return new OrderCreationInSAPOutput();
    }

    /**
     * Create an instance of {@link OrderCreationInSAPInput }
     * 
     */
    public OrderCreationInSAPInput createOrderCreationInSAPInput() {
        return new OrderCreationInSAPInput();
    }

    /**
     * Create an instance of {@link InOrderLines }
     * 
     */
    public InOrderLines createInOrderLines() {
        return new InOrderLines();
    }
    
    /**
     * Create an instance of {@link inOrderText }
     * 
     */
    public InOrderText createInOrderText() {
        return new InOrderText();
    }

    /**
     * Create an instance of {@link OutOrderLines }
     * 
     */
    public OutOrderLines createOutOrderLines() {
        return new OutOrderLines();
    }

    /**
     * Create an instance of {@link ScheduledLines }
     * 
     */
    public ScheduledLines createScheduledLines() {
        return new ScheduledLines();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderCreationInSAPInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_OrderCreate_v1/orderCreationInSAPWebservice", name = "orderCreationInSAPInput")
    public JAXBElement<OrderCreationInSAPInput> createOrderCreationInSAPInput(OrderCreationInSAPInput value) {
        return new JAXBElement<OrderCreationInSAPInput>(_OrderCreationInSAPInput_QNAME, OrderCreationInSAPInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderCreationInSAPOutput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_OrderCreate_v1/orderCreationInSAPWebservice", name = "orderCreationInSAPOutput")
    public JAXBElement<OrderCreationInSAPOutput> createOrderCreationInSAPOutput(OrderCreationInSAPOutput value) {
        return new JAXBElement<OrderCreationInSAPOutput>(_OrderCreationInSAPOutput_QNAME, OrderCreationInSAPOutput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Discounts", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesDiscounts(String value) {
        return new JAXBElement<String>(_OutOrderLinesDiscounts_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingPoint", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesShippingPoint(String value) {
        return new JAXBElement<String>(_OutOrderLinesShippingPoint_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FeeMin", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFeeMin(String value) {
        return new JAXBElement<String>(_OutOrderLinesFeeMin_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialEntered", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMaterialEntered(String value) {
        return new JAXBElement<String>(_OutOrderLinesMaterialEntered_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GrossPrice", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesGrossPrice(String value) {
        return new JAXBElement<String>(_OutOrderLinesGrossPrice_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Freight", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFreight(String value) {
        return new JAXBElement<String>(_OutOrderLinesFreight_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Message", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMessage(String value) {
        return new JAXBElement<String>(_OutOrderLinesMessage_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fee", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFee(String value) {
        return new JAXBElement<String>(_OutOrderLinesFee_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Handling", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHandling(String value) {
        return new JAXBElement<String>(_OutOrderLinesHandling_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BillingDeliveryBlock", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesBillingDeliveryBlock(String value) {
        return new JAXBElement<String>(_OutOrderLinesBillingDeliveryBlock_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tax", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesTax(String value) {
        return new JAXBElement<String>(_OutOrderLinesTax_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FreightAndHandling", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFreightAndHandling(String value) {
        return new JAXBElement<String>(_OutOrderLinesFreightAndHandling_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HSAPromotion", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHSAPromotion(String value) {
        return new JAXBElement<String>(_OutOrderLinesHSAPromotion_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DropShipFee", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesDropShipFee(String value) {
        return new JAXBElement<String>(_OutOrderLinesDropShipFee_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesLineNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesLineNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BaseUOM", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesBaseUOM(String value) {
        return new JAXBElement<String>(_OutOrderLinesBaseUOM_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceType", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesPriceType(String value) {
        return new JAXBElement<String>(_OutOrderLinesPriceType_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetValue", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesNetValue(String value) {
        return new JAXBElement<String>(_OutOrderLinesNetValue_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubstitutionReason", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesSubstitutionReason(String value) {
        return new JAXBElement<String>(_OutOrderLinesSubstitutionReason_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMaterialNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesMaterialNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesUOM", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesSalesUOM(String value) {
        return new JAXBElement<String>(_OutOrderLinesSalesUOM_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ItemCategory", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesItemCategory(String value) {
        return new JAXBElement<String>(_OutOrderLinesItemCategory_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HigherLevelItemNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHigherLevelItemNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesHigherLevelItemNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Route", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesRoute(String value) {
        return new JAXBElement<String>(_OutOrderLinesRoute_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AvailableQuantity", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesAvailableQuantity(String value) {
        return new JAXBElement<String>(_OutOrderLinesAvailableQuantity_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errorMessage", scope = OrderCreationInSAPOutput.class)
    public JAXBElement<String> createOrderCreationInSAPOutputErrorMessage(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPOutputErrorMessage_QNAME, String.class, OrderCreationInSAPOutput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_GatewayRelatedOrdernumber", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInGatewayRelatedOrdernumber(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInGatewayRelatedOrdernumber_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_HouseAccount", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInHouseAccount(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInHouseAccount_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardAccountNumber", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInCreditCardAccountNumber(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInCreditCardAccountNumber_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CustomerNotes", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInCustomerNotes(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInCustomerNotes_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_DealerPONumber", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInDealerPONumber(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInDealerPONumber_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_OrderReason", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInOrderReason(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInOrderReason_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_RequestedDeliveryDate", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInRequestedDeliveryDate(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInRequestedDeliveryDate_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardExpirationCard", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInCreditCardExpirationCard(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInCreditCardExpirationCard_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardType", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInCreditCardType(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInCreditCardType_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardSequenceNumber", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInCreditCardSequenceNumber(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInCreditCardSequenceNumber_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_HoldCode", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInHoldCode(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInHoldCode_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_BillToNumber", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInBillToNumber(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInBillToNumber_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingPoint", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesShippingPoint(String value) {
        return new JAXBElement<String>(_OutOrderLinesShippingPoint_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Plant", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesPlant(String value) {
        return new JAXBElement<String>(_InOrderLinesPlant_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lot", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesLot(String value) {
        return new JAXBElement<String>(_InOrderLinesLot_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnloadingPoint", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesUnloadingPoint(String value) {
        return new JAXBElement<String>(_InOrderLinesUnloadingPoint_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Route", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesRoute(String value) {
        return new JAXBElement<String>(_OutOrderLinesRoute_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerLineNumber", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesCustomerLineNumber(String value) {
        return new JAXBElement<String>(_InOrderLinesCustomerLineNumber_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScheduledLineNumber", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesScheduledLineNumber(String value) {
        return new JAXBElement<String>(_ScheduledLinesScheduledLineNumber_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesDeliveryDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesDeliveryDate_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineNumber", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesLineNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesLineNumber_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesQuantity(String value) {
        return new JAXBElement<String>(_ScheduledLinesQuantity_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesShipDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesShipDate_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineStatus", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesLineStatus(String value) {
        return new JAXBElement<String>(_ScheduledLinesLineStatus_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialAvailabilityDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesMaterialAvailabilityDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesMaterialAvailabilityDate_QNAME, String.class, ScheduledLines.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressName", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressName(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressName_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressStreet", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressStreet(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressStreet_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressStr_Suppl1", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressStrSuppl1(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressStrSuppl1r_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressCity", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressCity(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressCity_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressRegion", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressRegion(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressRegion_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressPostl_Cod1", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressPostlCod1(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressPostlCod1QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    @XmlElementDecl(namespace = "", name = "in_AddressCountry", scope = OrderCreationInSAPInput.class)
    public JAXBElement<String> createOrderCreationInSAPInputInAddressCountry(String value) {
        return new JAXBElement<String>(_OrderCreationInSAPInputInAddressCountry_QNAME, String.class, OrderCreationInSAPInput.class, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_ID", scope = InOrderText.class)
    public JAXBElement<String> createInOrderTextTEXTID(String value) {
        return new JAXBElement<String>(_InOrderTextTEXTID_QNAME, String.class, InOrderText.class, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_LINE", scope = InOrderText.class)
    public JAXBElement<String> createInOrderTextTEXTLINE(String value) {
        return new JAXBElement<String>(_InOrderTextTEXTLINE_QNAME, String.class, InOrderText.class, value);
    }

}
