//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 12:46:33 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_OrderCreate_v1/orderCreationInSAPWebservice")
package com.jnj.hcswmd01.mu007_epic_ordercreate_v1.ordercreationinsapwebservice;
