//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:57:15 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_ordersimulate_v1.ordersimulatewebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for in_orderLines complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="in_orderLines">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaterialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesUOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "in_orderLines", propOrder =
{ "materialNumber", "modCode", "quantity", "salesUOM","route" })
@XmlRootElement(name = "InOrderLines")
public class InOrderLines
{

	@XmlElement(name = "MaterialNumber", required = true, nillable = true)
	protected String materialNumber;
	@XmlElementRef(name = "ModCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> modCode;
	@XmlElement(name = "Quantity", required = true, nillable = true)
	protected String quantity;
	@XmlElement(name = "SalesUOM", required = true, nillable = true)
	protected String salesUOM;
    @XmlElement(name = "Route", required = true, nillable = true)
    protected String route;

	/**
	 * Gets the value of the materialNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaterialNumber()
	{
		return materialNumber;
	}

	/**
	 * Sets the value of the materialNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMaterialNumber(final String value)
	{
		this.materialNumber = value;
	}

	/**
	 * Gets the value of the modCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getModCode()
	{
		return modCode;
	}

	/**
	 * Sets the value of the modCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setModCode(final JAXBElement<String> value)
	{
		this.modCode = value;
	}

	/**
	 * Gets the value of the quantity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQuantity()
	{
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setQuantity(final String value)
	{
		this.quantity = value;
	}

	/**
	 * Gets the value of the salesUOM property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSalesUOM()
	{
		return salesUOM;
	}

	/**
	 * Sets the value of the salesUOM property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setSalesUOM(final String value)
	{
		this.salesUOM = value;
	}
	
	/**
	 * Gets the value of the route.
	 * @return
	 */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }
}
