//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:57:15 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_ordersimulate_v1.ordersimulatewebservice;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for orderLinesOutput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderLinesOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaterialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvailableQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GrossPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Discounts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BaseUOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesUOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaterialEntered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubstitutionReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HigherLevelItemNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItemCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnloadingPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HSAPromotion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreightHandling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DropShipFee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fee_Min" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Plant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduledLines" type="{http://hcswmd01.jnj.com/MU007_EPIC_OrderSimulate_v1/orderSimulateWebservice}scheduledLines" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderLinesOutput", propOrder =
{ "lineNumber", "materialNumber", "availableQuantity", "grossPrice", "discounts", "baseUOM", "salesUOM", "message", "status",
		"materialEntered", "substitutionReason", "higherLevelItemNumber", "itemCategory", "route", "unloadingPoint",
		"shippingPoint", "priceType", "hsaPromotion", "freightHandling", "dropShipFee", "feeMin", "netValue", "plant",
		"scheduledLines" })
@XmlRootElement(name = "OrderLinesOutput")
public class OrderLinesOutput
{

	@XmlElementRef(name = "LineNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> lineNumber;
	@XmlElementRef(name = "MaterialNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> materialNumber;
	@XmlElementRef(name = "AvailableQuantity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> availableQuantity;
	@XmlElementRef(name = "GrossPrice", type = JAXBElement.class, required = false)
	protected JAXBElement<String> grossPrice;
	@XmlElementRef(name = "Discounts", type = JAXBElement.class, required = false)
	protected JAXBElement<String> discounts;
	@XmlElementRef(name = "BaseUOM", type = JAXBElement.class, required = false)
	protected JAXBElement<String> baseUOM;
	@XmlElementRef(name = "SalesUOM", type = JAXBElement.class, required = false)
	protected JAXBElement<String> salesUOM;
	@XmlElementRef(name = "Message", type = JAXBElement.class, required = false)
	protected JAXBElement<String> message;
	@XmlElementRef(name = "Status", type = JAXBElement.class, required = false)
	protected JAXBElement<String> status;
	@XmlElementRef(name = "MaterialEntered", type = JAXBElement.class, required = false)
	protected JAXBElement<String> materialEntered;
	@XmlElementRef(name = "SubstitutionReason", type = JAXBElement.class, required = false)
	protected JAXBElement<String> substitutionReason;
	@XmlElementRef(name = "HigherLevelItemNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> higherLevelItemNumber;
	@XmlElementRef(name = "ItemCategory", type = JAXBElement.class, required = false)
	protected JAXBElement<String> itemCategory;
	@XmlElementRef(name = "Route", type = JAXBElement.class, required = false)
	protected JAXBElement<String> route;
	@XmlElementRef(name = "UnloadingPoint", type = JAXBElement.class, required = false)
	protected JAXBElement<String> unloadingPoint;
	@XmlElementRef(name = "ShippingPoint", type = JAXBElement.class, required = false)
	protected JAXBElement<String> shippingPoint;
	@XmlElementRef(name = "PriceType", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceType;
	@XmlElementRef(name = "HSAPromotion", type = JAXBElement.class, required = false)
	protected JAXBElement<String> hsaPromotion;
	@XmlElementRef(name = "FreightHandling", type = JAXBElement.class, required = false)
	protected JAXBElement<String> freightHandling;
	@XmlElementRef(name = "DropShipFee", type = JAXBElement.class, required = false)
	protected JAXBElement<String> dropShipFee;
	@XmlElementRef(name = "Fee_Min", type = JAXBElement.class, required = false)
	protected JAXBElement<String> feeMin;
	@XmlElementRef(name = "NetValue", type = JAXBElement.class, required = false)
	protected JAXBElement<String> netValue;
	@XmlElementRef(name = "Plant", type = JAXBElement.class, required = false)
	protected JAXBElement<String> plant;
	@XmlElement(nillable = true)
	protected List<ScheduledLines> scheduledLines;

	/**
	 * Gets the value of the lineNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getLineNumber()
	{
		return lineNumber;
	}

	/**
	 * Sets the value of the lineNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setLineNumber(final JAXBElement<String> value)
	{
		this.lineNumber = value;
	}

	/**
	 * Gets the value of the materialNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getMaterialNumber()
	{
		return materialNumber;
	}

	/**
	 * Sets the value of the materialNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setMaterialNumber(final JAXBElement<String> value)
	{
		this.materialNumber = value;
	}

	/**
	 * Gets the value of the availableQuantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getAvailableQuantity()
	{
		return availableQuantity;
	}

	/**
	 * Sets the value of the availableQuantity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setAvailableQuantity(final JAXBElement<String> value)
	{
		this.availableQuantity = value;
	}

	/**
	 * Gets the value of the grossPrice property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getGrossPrice()
	{
		return grossPrice;
	}

	/**
	 * Sets the value of the grossPrice property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setGrossPrice(final JAXBElement<String> value)
	{
		this.grossPrice = value;
	}

	/**
	 * Gets the value of the discounts property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getDiscounts()
	{
		return discounts;
	}

	/**
	 * Sets the value of the discounts property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setDiscounts(final JAXBElement<String> value)
	{
		this.discounts = value;
	}

	/**
	 * Gets the value of the baseUOM property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getBaseUOM()
	{
		return baseUOM;
	}

	/**
	 * Sets the value of the baseUOM property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setBaseUOM(final JAXBElement<String> value)
	{
		this.baseUOM = value;
	}

	/**
	 * Gets the value of the salesUOM property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSalesUOM()
	{
		return salesUOM;
	}

	/**
	 * Sets the value of the salesUOM property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSalesUOM(final JAXBElement<String> value)
	{
		this.salesUOM = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getMessage()
	{
		return message;
	}

	/**
	 * Sets the value of the message property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setMessage(final JAXBElement<String> value)
	{
		this.message = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setStatus(final JAXBElement<String> value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the materialEntered property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getMaterialEntered()
	{
		return materialEntered;
	}

	/**
	 * Sets the value of the materialEntered property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setMaterialEntered(final JAXBElement<String> value)
	{
		this.materialEntered = value;
	}

	/**
	 * Gets the value of the substitutionReason property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSubstitutionReason()
	{
		return substitutionReason;
	}

	/**
	 * Sets the value of the substitutionReason property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSubstitutionReason(final JAXBElement<String> value)
	{
		this.substitutionReason = value;
	}

	/**
	 * Gets the value of the higherLevelItemNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getHigherLevelItemNumber()
	{
		return higherLevelItemNumber;
	}

	/**
	 * Sets the value of the higherLevelItemNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setHigherLevelItemNumber(final JAXBElement<String> value)
	{
		this.higherLevelItemNumber = value;
	}

	/**
	 * Gets the value of the itemCategory property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getItemCategory()
	{
		return itemCategory;
	}

	/**
	 * Sets the value of the itemCategory property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setItemCategory(final JAXBElement<String> value)
	{
		this.itemCategory = value;
	}

	/**
	 * Gets the value of the route property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getRoute()
	{
		return route;
	}

	/**
	 * Sets the value of the route property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setRoute(final JAXBElement<String> value)
	{
		this.route = value;
	}

	/**
	 * Gets the value of the unloadingPoint property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUnloadingPoint()
	{
		return unloadingPoint;
	}

	/**
	 * Sets the value of the unloadingPoint property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUnloadingPoint(final JAXBElement<String> value)
	{
		this.unloadingPoint = value;
	}

	/**
	 * Gets the value of the shippingPoint property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getShippingPoint()
	{
		return shippingPoint;
	}

	/**
	 * Sets the value of the shippingPoint property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setShippingPoint(final JAXBElement<String> value)
	{
		this.shippingPoint = value;
	}

	/**
	 * Gets the value of the priceType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceType()
	{
		return priceType;
	}

	/**
	 * Sets the value of the priceType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceType(final JAXBElement<String> value)
	{
		this.priceType = value;
	}

	/**
	 * Gets the value of the hsaPromotion property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getHSAPromotion()
	{
		return hsaPromotion;
	}

	/**
	 * Sets the value of the hsaPromotion property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setHSAPromotion(final JAXBElement<String> value)
	{
		this.hsaPromotion = value;
	}

	/**
	 * Gets the value of the freightHandling property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getFreightHandling()
	{
		return freightHandling;
	}

	/**
	 * Sets the value of the freightHandling property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setFreightHandling(final JAXBElement<String> value)
	{
		this.freightHandling = value;
	}

	/**
	 * Gets the value of the dropShipFee property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getDropShipFee()
	{
		return dropShipFee;
	}

	/**
	 * Sets the value of the dropShipFee property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setDropShipFee(final JAXBElement<String> value)
	{
		this.dropShipFee = value;
	}

	/**
	 * Gets the value of the feeMin property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getFeeMin()
	{
		return feeMin;
	}

	/**
	 * Sets the value of the feeMin property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setFeeMin(final JAXBElement<String> value)
	{
		this.feeMin = value;
	}

	/**
	 * Gets the value of the netValue property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getNetValue()
	{
		return netValue;
	}

	/**
	 * Sets the value of the netValue property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setNetValue(final JAXBElement<String> value)
	{
		this.netValue = value;
	}

	/**
	 * Gets the value of the plant property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPlant()
	{
		return plant;
	}

	/**
	 * Sets the value of the plant property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPlant(final JAXBElement<String> value)
	{
		this.plant = value;
	}

	/**
	 * Gets the value of the scheduledLines property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the scheduledLines property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getScheduledLines().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ScheduledLines }
	 * 
	 * 
	 */
	public List<ScheduledLines> getScheduledLines()
	{
		if (scheduledLines == null)
		{
			scheduledLines = new ArrayList<ScheduledLines>();
		}
		return this.scheduledLines;
	}

}
