//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:53:24 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_orderreturn_v1.orderreturnwebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for in_orderLines complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="in_orderLines">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaterialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QuantityReturned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesUOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Lot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InvoiceLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PONumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "in_orderLines", propOrder = {
    "materialNumber",
    "quantityReturned",
    "salesUOM",
    "lot",
    "invoiceNumber",
    "invoiceLine",
    "poNumber"
})
@XmlRootElement(name = "InOrderLines")
public class InOrderLines {

    @XmlElement(name = "MaterialNumber", required = true, nillable = true)
    protected String materialNumber;
    @XmlElement(name = "QuantityReturned", required = true, nillable = true)
    protected String quantityReturned;
    @XmlElementRef(name = "SalesUOM", type = JAXBElement.class, required = false)
    protected JAXBElement<String> salesUOM;
    @XmlElementRef(name = "Lot", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lot;
    @XmlElementRef(name = "InvoiceNumber", type = JAXBElement.class, required = false)
    protected JAXBElement<String> invoiceNumber;
    @XmlElementRef(name = "InvoiceLine", type = JAXBElement.class, required = false)
    protected JAXBElement<String> invoiceLine;
    @XmlElementRef(name = "PONumber", type = JAXBElement.class, required = false)
    protected JAXBElement<String> poNumber;

    /**
     * Gets the value of the materialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialNumber() {
        return materialNumber;
    }

    /**
     * Sets the value of the materialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialNumber(final String value) {
        this.materialNumber = value;
    }

    /**
     * Gets the value of the quantityReturned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityReturned() {
        return quantityReturned;
    }

    /**
     * Sets the value of the quantityReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityReturned(final String value) {
        this.quantityReturned = value;
    }

    /**
     * Gets the value of the salesUOM property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSalesUOM() {
        return salesUOM;
    }

    /**
     * Sets the value of the salesUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSalesUOM(final JAXBElement<String> value) {
        this.salesUOM = value;
    }

    /**
     * Gets the value of the lot property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLot() {
        return lot;
    }

    /**
     * Sets the value of the lot property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLot(final JAXBElement<String> value) {
        this.lot = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInvoiceNumber(final JAXBElement<String> value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceLine property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInvoiceLine() {
        return invoiceLine;
    }

    /**
     * Sets the value of the invoiceLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInvoiceLine(final JAXBElement<String> value) {
        this.invoiceLine = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPONumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPONumber(final JAXBElement<String> value) {
        this.poNumber = value;
    }

}
