//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:53:24 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_orderreturn_v1.orderreturnwebservice;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for orderReturnInSAPOutput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderReturnInSAPOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="out_SalesOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="out_orderLines" type="{http://hcswmd01.jnj.com/MU007_EPIC_OrderReturn_v1/orderReturnWebservice}out_orderLines" maxOccurs="unbounded"/>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderReturnInSAPOutput", propOrder =
{ "status", "outSalesOrderNumber", "outOrderLines", "errorMessage" })
@XmlRootElement(name = "OrderReturnInSAPOutput")
public class OrderReturnInSAPOutput
{

	@XmlElement(name = "Status", required = true, nillable = true)
	protected String status;
	@XmlElement(name = "out_SalesOrderNumber", required = true, nillable = true)
	protected String outSalesOrderNumber;
	@XmlElement(name = "out_orderLines", required = true, nillable = true)
	protected List<OutOrderLines> outOrderLines;
	@XmlElementRef(name = "errorMessage", type = JAXBElement.class, required = false)
	protected JAXBElement<String> errorMessage;

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setStatus(final String value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the outSalesOrderNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOutSalesOrderNumber()
	{
		return outSalesOrderNumber;
	}

	/**
	 * Sets the value of the outSalesOrderNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setOutSalesOrderNumber(final String value)
	{
		this.outSalesOrderNumber = value;
	}

	/**
	 * Gets the value of the outOrderLines property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the outOrderLines property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOutOrderLines().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OutOrderLines }
	 * 
	 * 
	 */
	public List<OutOrderLines> getOutOrderLines()
	{
		if (outOrderLines == null)
		{
			outOrderLines = new ArrayList<OutOrderLines>();
		}
		return this.outOrderLines;
	}

	/**
	 * Gets the value of the errorMessage property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getErrorMessage()
	{
		return errorMessage;
	}

	/**
	 * Sets the value of the errorMessage property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setErrorMessage(final JAXBElement<String> value)
	{
		this.errorMessage = value;
	}

}
