//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:59:17 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_viewconsstock_v1.viewconsignmentstockwebservice;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for Consignment_OUT complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Consignment_OUT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MATERIAL_OUT" type="{http://hcswmd01.jnj.com/MU007_EPIC_ViewConsStock_v1/viewConsignmentStockWebservice}MATERIAL_OUT" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Consignment_OUT", propOrder =
{ "materialout" })
@XmlRootElement(name = "ConsignmentOUT")
public class ConsignmentOUT
{

	@XmlElement(name = "MATERIAL_OUT", required = true, nillable = true)
	protected List<MATERIALOUT> materialout;

	/**
	 * Gets the value of the materialout property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the materialout property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMATERIALOUT().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link MATERIALOUT }
	 * 
	 * 
	 */
	public List<MATERIALOUT> getMATERIALOUT()
	{
		if (materialout == null)
		{
			materialout = new ArrayList<MATERIALOUT>();
		}
		return this.materialout;
	}

}
