//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:59:17 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_viewconsstock_v1.viewconsignmentstockwebservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for MATERIAL_OUT complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MATERIAL_OUT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUST_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MAT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BATCH_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UNRSTRCTD_STOCK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QUALITY_STOCK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RSTRCTD_STOCK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOTAL_STOCK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MATERIAL_OUT", propOrder =
{ "custnumber", "matnumber", "batchnumber", "unrstrctdstock", "qualitystock", "rstrctdstock", "totalstock", "uom", "type",
		"message" })
@XmlRootElement(name = "MATERIALOUT")
public class MATERIALOUT
{

	@XmlElement(name = "CUST_NUMBER", required = true, nillable = true)
	protected String custnumber;
	@XmlElement(name = "MAT_NUMBER", required = true, nillable = true)
	protected String matnumber;
	@XmlElement(name = "BATCH_NUMBER", required = true, nillable = true)
	protected String batchnumber;
	@XmlElement(name = "UNRSTRCTD_STOCK", required = true, nillable = true)
	protected String unrstrctdstock;
	@XmlElement(name = "QUALITY_STOCK", required = true, nillable = true)
	protected String qualitystock;
	@XmlElement(name = "RSTRCTD_STOCK", required = true, nillable = true)
	protected String rstrctdstock;
	@XmlElement(name = "TOTAL_STOCK", required = true, nillable = true)
	protected String totalstock;
	@XmlElement(name = "UOM", required = true, nillable = true)
	protected String uom;
	@XmlElement(name = "TYPE", required = true, nillable = true)
	protected String type;
	@XmlElement(name = "MESSAGE", required = true, nillable = true)
	protected String message;

	/**
	 * Gets the value of the custnumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCUSTNUMBER()
	{
		return custnumber;
	}

	/**
	 * Sets the value of the custnumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setCUSTNUMBER(final String value)
	{
		this.custnumber = value;
	}

	/**
	 * Gets the value of the matnumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMATNUMBER()
	{
		return matnumber;
	}

	/**
	 * Sets the value of the matnumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMATNUMBER(final String value)
	{
		this.matnumber = value;
	}

	/**
	 * Gets the value of the batchnumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBATCHNUMBER()
	{
		return batchnumber;
	}

	/**
	 * Sets the value of the batchnumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setBATCHNUMBER(final String value)
	{
		this.batchnumber = value;
	}

	/**
	 * Gets the value of the unrstrctdstock property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUNRSTRCTDSTOCK()
	{
		return unrstrctdstock;
	}

	/**
	 * Sets the value of the unrstrctdstock property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setUNRSTRCTDSTOCK(final String value)
	{
		this.unrstrctdstock = value;
	}

	/**
	 * Gets the value of the qualitystock property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQUALITYSTOCK()
	{
		return qualitystock;
	}

	/**
	 * Sets the value of the qualitystock property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setQUALITYSTOCK(final String value)
	{
		this.qualitystock = value;
	}

	/**
	 * Gets the value of the rstrctdstock property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRSTRCTDSTOCK()
	{
		return rstrctdstock;
	}

	/**
	 * Sets the value of the rstrctdstock property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setRSTRCTDSTOCK(final String value)
	{
		this.rstrctdstock = value;
	}

	/**
	 * Gets the value of the totalstock property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTOTALSTOCK()
	{
		return totalstock;
	}

	/**
	 * Sets the value of the totalstock property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setTOTALSTOCK(final String value)
	{
		this.totalstock = value;
	}

	/**
	 * Gets the value of the uom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUOM()
	{
		return uom;
	}

	/**
	 * Sets the value of the uom property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setUOM(final String value)
	{
		this.uom = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTYPE()
	{
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setTYPE(final String value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMESSAGE()
	{
		return message;
	}

	/**
	 * Sets the value of the message property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMESSAGE(final String value)
	{
		this.message = value;
	}

}
