//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:59:17 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_viewconsstock_v1.viewconsignmentstockwebservice;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for PLANT_IN complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PLANT_IN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SIGN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LOW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HIGH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PLANT_IN", propOrder =
{ "sign", "option", "low", "high" })
@XmlRootElement(name = "PLANTIN")
public class PLANTIN
{

	@XmlElement(name = "SIGN", required = true, nillable = true)
	protected String sign;
	@XmlElement(name = "OPTION", required = true, nillable = true)
	protected String option;
	@XmlElement(name = "LOW", required = true, nillable = true)
	protected String low;
	@XmlElement(name = "HIGH", required = true, nillable = true)
	protected String high;

	/**
	 * Gets the value of the sign property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSIGN()
	{
		return sign;
	}

	/**
	 * Sets the value of the sign property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setSIGN(final String value)
	{
		this.sign = value;
	}

	/**
	 * Gets the value of the option property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOPTION()
	{
		return option;
	}

	/**
	 * Sets the value of the option property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setOPTION(final String value)
	{
		this.option = value;
	}

	/**
	 * Gets the value of the low property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLOW()
	{
		return low;
	}

	/**
	 * Sets the value of the low property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setLOW(final String value)
	{
		this.low = value;
	}

	/**
	 * Gets the value of the high property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHIGH()
	{
		return high;
	}

	/**
	 * Sets the value of the high property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setHIGH(final String value)
	{
		this.high = value;
	}

}
