//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:59:17 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_viewconsstock_v1.viewconsignmentstockwebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for viewConsignmentStockInput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="viewConsignmentStockInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Consignment_IN" type="{http://hcswmd01.jnj.com/MU007_EPIC_ViewConsStock_v1/viewConsignmentStockWebservice}Consignment_IN"/>
 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "viewConsignmentStockInput", propOrder =
{ "consignmentIN", "transactionID" })
@XmlRootElement(name = "ViewConsignmentStockInput")
public class ViewConsignmentStockInput
{

	@XmlElement(name = "Consignment_IN", required = true, nillable = true)
	protected ConsignmentIN consignmentIN;
	@XmlElementRef(name = "transactionID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> transactionID;

	/**
	 * Gets the value of the consignmentIN property.
	 * 
	 * @return possible object is {@link ConsignmentIN }
	 * 
	 */
	public ConsignmentIN getConsignmentIN()
	{
		return consignmentIN;
	}

	/**
	 * Sets the value of the consignmentIN property.
	 * 
	 * @param value
	 *           allowed object is {@link ConsignmentIN }
	 * 
	 */
	public void setConsignmentIN(final ConsignmentIN value)
	{
		this.consignmentIN = value;
	}

	/**
	 * Gets the value of the transactionID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getTransactionID()
	{
		return transactionID;
	}

	/**
	 * Sets the value of the transactionID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setTransactionID(final JAXBElement<String> value)
	{
		this.transactionID = value;
	}

}
