
package com.jnj.itsusral00725.pu023_atlas_sn_verification_v1_webservices.snverificationrequestresponse;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PU023_ATLAS_SN_Verification_v1.webservices.SNVerificationRequestResponse", targetNamespace = "http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", wsdlLocation = "http://gpsgisnad.jnj.com/ws/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse?WSDL")
public class PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse
    extends Service
{

    private final static URL PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_WSDL_LOCATION;
    private final static WebServiceException PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_EXCEPTION;
    private final static QName PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_QNAME = new QName("http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", "PU023_ATLAS_SN_Verification_v1.webservices.SNVerificationRequestResponse");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = URI.create("http://gpsgisnad.jnj.com/ws/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse?WSDL").toURL();
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_WSDL_LOCATION = url;
        PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_EXCEPTION = e;
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse() {
        super(__getWsdlLocation(), PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_QNAME);
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse(WebServiceFeature... features) {
        super(__getWsdlLocation(), PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_QNAME, features);
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse(URL wsdlLocation) {
        super(wsdlLocation, PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_QNAME);
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_QNAME, features);
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponse(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SNVerificationRequestResponsePortType
     */
    @WebEndpoint(name = "PU023_ATLAS_SN_Verification_v1_webservices_SNVerificationRequestResponse_Port")
    public SNVerificationRequestResponsePortType getPU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponsePort() {
        return super.getPort(new QName("http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", "PU023_ATLAS_SN_Verification_v1_webservices_SNVerificationRequestResponse_Port"), SNVerificationRequestResponsePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SNVerificationRequestResponsePortType
     */
    @WebEndpoint(name = "PU023_ATLAS_SN_Verification_v1_webservices_SNVerificationRequestResponse_Port")
    public SNVerificationRequestResponsePortType getPU023ATLASSNVerificationV1WebservicesSNVerificationRequestResponsePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", "PU023_ATLAS_SN_Verification_v1_webservices_SNVerificationRequestResponse_Port"), SNVerificationRequestResponsePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_EXCEPTION!= null) {
            throw PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_EXCEPTION;
        }
        return PU023ATLASSNVERIFICATIONV1WEBSERVICESSNVERIFICATIONREQUESTRESPONSE_WSDL_LOCATION;
    }

}
