//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.04 at 03:20:45 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btbepic_in2903_ordercreate_hybris_source_v1_webservices.createorder_ws;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for inDataHeader complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inDataHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in_Request_Type" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_Request_Type" minOccurs="0"/>
 *         &lt;element name="in_SalesOrganization" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_SalesOrganization" minOccurs="0"/>
 *         &lt;element name="in_DistributionChannel" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_DistributionChannel" minOccurs="0"/>
 *         &lt;element name="in_Division" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_Division" minOccurs="0"/>
 *         &lt;element name="in_OrderType" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_OrderType" minOccurs="0"/>
 *         &lt;element name="in_SoldToNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_SoldToNumber" minOccurs="0"/>
 *         &lt;element name="in_ShipToNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToNumber" minOccurs="0"/>
 *         &lt;element name="in_ShipToName" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToName" minOccurs="0"/>
 *         &lt;element name="in_ShipToAddress1" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToAddress1" minOccurs="0"/>
 *         &lt;element name="in_ShipToAddress2" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToAddress2" minOccurs="0"/>
 *         &lt;element name="in_ShipToCity" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToCity" minOccurs="0"/>
 *         &lt;element name="in_ShipToState" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToState" minOccurs="0"/>
 *         &lt;element name="in_ShipToPostalCd" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToPostalCd" minOccurs="0"/>
 *         &lt;element name="in_ShipToCountry" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ShipToCountry" minOccurs="0"/>
 *         &lt;element name="in_BillToNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_BillToNumber" minOccurs="0"/>
 *         &lt;element name="in_HouseAccount" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_HouseAccount" minOccurs="0"/>
 *         &lt;element name="in_CustomerPortalOrdernumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CustomerPortalOrdernumber" minOccurs="0"/>
 *         &lt;element name="in_PONumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_PONumber" minOccurs="0"/>
 *         &lt;element name="in_PODate" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_PODate" minOccurs="0"/>
 *         &lt;element name="in_OrderChannel" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_OrderChannel" minOccurs="0"/>
 *         &lt;element name="in_OrderSource" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_OrderSource" minOccurs="0"/>
 *         &lt;element name="in_OrderReason" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_OrderReason" minOccurs="0"/>
 *         &lt;element name="in_ContactName" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ContactName" minOccurs="0"/>
 *         &lt;element name="in_ContactPhoneNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ContactPhoneNumber" minOccurs="0"/>
 *         &lt;element name="in_ContactEmail" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ContactEmail" minOccurs="0"/>
 *         &lt;element name="in_RequestedDeliveryDate" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_RequestedDeliveryDate" minOccurs="0"/>
 *         &lt;element name="in_CompleteDelivery" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CompleteDelivery" minOccurs="0"/>
 *         &lt;element name="in_ContractReferenceNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ContractReferenceNumber" minOccurs="0"/>
 *         &lt;element name="in_ForbiddenSales" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_ForbiddenSales" minOccurs="0"/>
 *         &lt;element name="in_DropShipIndicator" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_DropShipIndicator" minOccurs="0"/>
 *         &lt;element name="in_DealerPONumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_DealerPONumber" minOccurs="0"/>
 *         &lt;element name="in_HoldCode" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_HoldCode" minOccurs="0"/>
 *         &lt;element name="in_CustomerNotes" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CustomerNotes" minOccurs="0"/>
 *         &lt;element name="in_CreditCardSequenceNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CreditCardSequenceNumber" minOccurs="0"/>
 *         &lt;element name="in_CreditCardAccountNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CreditCardAccountNumber" minOccurs="0"/>
 *         &lt;element name="in_CreditCardExpirationCard" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CreditCardExpirationCard" minOccurs="0"/>
 *         &lt;element name="in_CreditCardType" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}in_CreditCardType" minOccurs="0"/>
 *         &lt;element name="inDataLineItem" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}inDataLineItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inDataHeader", propOrder =
{ "inRequestType", "inSalesOrganization", "inDistributionChannel", "inDivision", "inOrderType", "inSoldToNumber",
		"inShipToNumber", "inShipToName", "inShipToAddress1", "inShipToAddress2", "inShipToCity", "inShipToState",
		"inShipToPostalCd", "inShipToCountry", "inBillToNumber", "inHouseAccount", "inCustomerPortalOrdernumber", "inPONumber",
		"inPODate", "inOrderChannel", "inOrderSource", "inOrderReason", "inContactName", "inContactPhoneNumber", "inContactEmail",
		"inRequestedDeliveryDate", "inCompleteDelivery", "inContractReferenceNumber", "inForbiddenSales", "inDropShipIndicator",
		"inDealerPONumber", "inHoldCode", "inCustomerNotes", "inCreditCardSequenceNumber", "inCreditCardAccountNumber",
		"inCreditCardExpirationCard", "inCreditCardType", "inDataLineItem" })
@XmlRootElement(name = "InDataHeader")
public class InDataHeader
{

	@XmlElementRef(name = "in_Request_Type", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inRequestType;
	@XmlElementRef(name = "in_SalesOrganization", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inSalesOrganization;
	@XmlElementRef(name = "in_DistributionChannel", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inDistributionChannel;
	@XmlElementRef(name = "in_Division", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inDivision;
	@XmlElementRef(name = "in_OrderType", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inOrderType;
	@XmlElementRef(name = "in_SoldToNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inSoldToNumber;
	@XmlElementRef(name = "in_ShipToNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToNumber;
	@XmlElementRef(name = "in_ShipToName", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToName;
	@XmlElementRef(name = "in_ShipToAddress1", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToAddress1;
	@XmlElementRef(name = "in_ShipToAddress2", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToAddress2;
	@XmlElementRef(name = "in_ShipToCity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToCity;
	@XmlElementRef(name = "in_ShipToState", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToState;
	@XmlElementRef(name = "in_ShipToPostalCd", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToPostalCd;
	@XmlElementRef(name = "in_ShipToCountry", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inShipToCountry;
	@XmlElementRef(name = "in_BillToNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inBillToNumber;
	@XmlElementRef(name = "in_HouseAccount", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inHouseAccount;
	@XmlElementRef(name = "in_CustomerPortalOrdernumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCustomerPortalOrdernumber;
	@XmlElementRef(name = "in_PONumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inPONumber;
	@XmlElementRef(name = "in_PODate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inPODate;
	@XmlElementRef(name = "in_OrderChannel", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inOrderChannel;
	@XmlElementRef(name = "in_OrderSource", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inOrderSource;
	@XmlElementRef(name = "in_OrderReason", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inOrderReason;
	@XmlElementRef(name = "in_ContactName", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inContactName;
	@XmlElementRef(name = "in_ContactPhoneNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inContactPhoneNumber;
	@XmlElementRef(name = "in_ContactEmail", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inContactEmail;
	@XmlElementRef(name = "in_RequestedDeliveryDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inRequestedDeliveryDate;
	@XmlElementRef(name = "in_CompleteDelivery", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCompleteDelivery;
	@XmlElementRef(name = "in_ContractReferenceNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inContractReferenceNumber;
	@XmlElementRef(name = "in_ForbiddenSales", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inForbiddenSales;
	@XmlElementRef(name = "in_DropShipIndicator", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inDropShipIndicator;
	@XmlElementRef(name = "in_DealerPONumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inDealerPONumber;
	@XmlElementRef(name = "in_HoldCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inHoldCode;
	@XmlElementRef(name = "in_CustomerNotes", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCustomerNotes;
	@XmlElementRef(name = "in_CreditCardSequenceNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCreditCardSequenceNumber;
	@XmlElementRef(name = "in_CreditCardAccountNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCreditCardAccountNumber;
	@XmlElementRef(name = "in_CreditCardExpirationCard", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCreditCardExpirationCard;
	@XmlElementRef(name = "in_CreditCardType", type = JAXBElement.class, required = false)
	protected JAXBElement<String> inCreditCardType;
	@XmlElement(required = true)
	protected List<InDataLineItem> inDataLineItem;

	/**
	 * Gets the value of the inRequestType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInRequestType()
	{
		return inRequestType;
	}

	/**
	 * Sets the value of the inRequestType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInRequestType(final JAXBElement<String> value)
	{
		this.inRequestType = value;
	}

	/**
	 * Gets the value of the inSalesOrganization property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInSalesOrganization()
	{
		return inSalesOrganization;
	}

	/**
	 * Sets the value of the inSalesOrganization property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInSalesOrganization(final JAXBElement<String> value)
	{
		this.inSalesOrganization = value;
	}

	/**
	 * Gets the value of the inDistributionChannel property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInDistributionChannel()
	{
		return inDistributionChannel;
	}

	/**
	 * Sets the value of the inDistributionChannel property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInDistributionChannel(final JAXBElement<String> value)
	{
		this.inDistributionChannel = value;
	}

	/**
	 * Gets the value of the inDivision property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInDivision()
	{
		return inDivision;
	}

	/**
	 * Sets the value of the inDivision property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInDivision(final JAXBElement<String> value)
	{
		this.inDivision = value;
	}

	/**
	 * Gets the value of the inOrderType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInOrderType()
	{
		return inOrderType;
	}

	/**
	 * Sets the value of the inOrderType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInOrderType(final JAXBElement<String> value)
	{
		this.inOrderType = value;
	}

	/**
	 * Gets the value of the inSoldToNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInSoldToNumber()
	{
		return inSoldToNumber;
	}

	/**
	 * Sets the value of the inSoldToNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInSoldToNumber(final JAXBElement<String> value)
	{
		this.inSoldToNumber = value;
	}

	/**
	 * Gets the value of the inShipToNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToNumber()
	{
		return inShipToNumber;
	}

	/**
	 * Sets the value of the inShipToNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToNumber(final JAXBElement<String> value)
	{
		this.inShipToNumber = value;
	}

	/**
	 * Gets the value of the inShipToName property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToName()
	{
		return inShipToName;
	}

	/**
	 * Sets the value of the inShipToName property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToName(final JAXBElement<String> value)
	{
		this.inShipToName = value;
	}

	/**
	 * Gets the value of the inShipToAddress1 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToAddress1()
	{
		return inShipToAddress1;
	}

	/**
	 * Sets the value of the inShipToAddress1 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToAddress1(final JAXBElement<String> value)
	{
		this.inShipToAddress1 = value;
	}

	/**
	 * Gets the value of the inShipToAddress2 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToAddress2()
	{
		return inShipToAddress2;
	}

	/**
	 * Sets the value of the inShipToAddress2 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToAddress2(final JAXBElement<String> value)
	{
		this.inShipToAddress2 = value;
	}

	/**
	 * Gets the value of the inShipToCity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToCity()
	{
		return inShipToCity;
	}

	/**
	 * Sets the value of the inShipToCity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToCity(final JAXBElement<String> value)
	{
		this.inShipToCity = value;
	}

	/**
	 * Gets the value of the inShipToState property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToState()
	{
		return inShipToState;
	}

	/**
	 * Sets the value of the inShipToState property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToState(final JAXBElement<String> value)
	{
		this.inShipToState = value;
	}

	/**
	 * Gets the value of the inShipToPostalCd property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToPostalCd()
	{
		return inShipToPostalCd;
	}

	/**
	 * Sets the value of the inShipToPostalCd property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToPostalCd(final JAXBElement<String> value)
	{
		this.inShipToPostalCd = value;
	}

	/**
	 * Gets the value of the inShipToCountry property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInShipToCountry()
	{
		return inShipToCountry;
	}

	/**
	 * Sets the value of the inShipToCountry property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInShipToCountry(final JAXBElement<String> value)
	{
		this.inShipToCountry = value;
	}

	/**
	 * Gets the value of the inBillToNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInBillToNumber()
	{
		return inBillToNumber;
	}

	/**
	 * Sets the value of the inBillToNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInBillToNumber(final JAXBElement<String> value)
	{
		this.inBillToNumber = value;
	}

	/**
	 * Gets the value of the inHouseAccount property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInHouseAccount()
	{
		return inHouseAccount;
	}

	/**
	 * Sets the value of the inHouseAccount property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInHouseAccount(final JAXBElement<String> value)
	{
		this.inHouseAccount = value;
	}

	/**
	 * Gets the value of the inCustomerPortalOrdernumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCustomerPortalOrdernumber()
	{
		return inCustomerPortalOrdernumber;
	}

	/**
	 * Sets the value of the inCustomerPortalOrdernumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCustomerPortalOrdernumber(final JAXBElement<String> value)
	{
		this.inCustomerPortalOrdernumber = value;
	}

	/**
	 * Gets the value of the inPONumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInPONumber()
	{
		return inPONumber;
	}

	/**
	 * Sets the value of the inPONumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInPONumber(final JAXBElement<String> value)
	{
		this.inPONumber = value;
	}

	/**
	 * Gets the value of the inPODate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInPODate()
	{
		return inPODate;
	}

	/**
	 * Sets the value of the inPODate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInPODate(final JAXBElement<String> value)
	{
		this.inPODate = value;
	}

	/**
	 * Gets the value of the inOrderChannel property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInOrderChannel()
	{
		return inOrderChannel;
	}

	/**
	 * Sets the value of the inOrderChannel property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInOrderChannel(final JAXBElement<String> value)
	{
		this.inOrderChannel = value;
	}

	/**
	 * Gets the value of the inOrderSource property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInOrderSource()
	{
		return inOrderSource;
	}

	/**
	 * Sets the value of the inOrderSource property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInOrderSource(final JAXBElement<String> value)
	{
		this.inOrderSource = value;
	}

	/**
	 * Gets the value of the inOrderReason property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInOrderReason()
	{
		return inOrderReason;
	}

	/**
	 * Sets the value of the inOrderReason property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInOrderReason(final JAXBElement<String> value)
	{
		this.inOrderReason = value;
	}

	/**
	 * Gets the value of the inContactName property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInContactName()
	{
		return inContactName;
	}

	/**
	 * Sets the value of the inContactName property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInContactName(final JAXBElement<String> value)
	{
		this.inContactName = value;
	}

	/**
	 * Gets the value of the inContactPhoneNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInContactPhoneNumber()
	{
		return inContactPhoneNumber;
	}

	/**
	 * Sets the value of the inContactPhoneNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInContactPhoneNumber(final JAXBElement<String> value)
	{
		this.inContactPhoneNumber = value;
	}

	/**
	 * Gets the value of the inContactEmail property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInContactEmail()
	{
		return inContactEmail;
	}

	/**
	 * Sets the value of the inContactEmail property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInContactEmail(final JAXBElement<String> value)
	{
		this.inContactEmail = value;
	}

	/**
	 * Gets the value of the inRequestedDeliveryDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInRequestedDeliveryDate()
	{
		return inRequestedDeliveryDate;
	}

	/**
	 * Sets the value of the inRequestedDeliveryDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInRequestedDeliveryDate(final JAXBElement<String> value)
	{
		this.inRequestedDeliveryDate = value;
	}

	/**
	 * Gets the value of the inCompleteDelivery property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCompleteDelivery()
	{
		return inCompleteDelivery;
	}

	/**
	 * Sets the value of the inCompleteDelivery property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCompleteDelivery(final JAXBElement<String> value)
	{
		this.inCompleteDelivery = value;
	}

	/**
	 * Gets the value of the inContractReferenceNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInContractReferenceNumber()
	{
		return inContractReferenceNumber;
	}

	/**
	 * Sets the value of the inContractReferenceNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInContractReferenceNumber(final JAXBElement<String> value)
	{
		this.inContractReferenceNumber = value;
	}

	/**
	 * Gets the value of the inForbiddenSales property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInForbiddenSales()
	{
		return inForbiddenSales;
	}

	/**
	 * Sets the value of the inForbiddenSales property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInForbiddenSales(final JAXBElement<String> value)
	{
		this.inForbiddenSales = value;
	}

	/**
	 * Gets the value of the inDropShipIndicator property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInDropShipIndicator()
	{
		return inDropShipIndicator;
	}

	/**
	 * Sets the value of the inDropShipIndicator property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInDropShipIndicator(final JAXBElement<String> value)
	{
		this.inDropShipIndicator = value;
	}

	/**
	 * Gets the value of the inDealerPONumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInDealerPONumber()
	{
		return inDealerPONumber;
	}

	/**
	 * Sets the value of the inDealerPONumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInDealerPONumber(final JAXBElement<String> value)
	{
		this.inDealerPONumber = value;
	}

	/**
	 * Gets the value of the inHoldCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInHoldCode()
	{
		return inHoldCode;
	}

	/**
	 * Sets the value of the inHoldCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInHoldCode(final JAXBElement<String> value)
	{
		this.inHoldCode = value;
	}

	/**
	 * Gets the value of the inCustomerNotes property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCustomerNotes()
	{
		return inCustomerNotes;
	}

	/**
	 * Sets the value of the inCustomerNotes property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCustomerNotes(final JAXBElement<String> value)
	{
		this.inCustomerNotes = value;
	}

	/**
	 * Gets the value of the inCreditCardSequenceNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCreditCardSequenceNumber()
	{
		return inCreditCardSequenceNumber;
	}

	/**
	 * Sets the value of the inCreditCardSequenceNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCreditCardSequenceNumber(final JAXBElement<String> value)
	{
		this.inCreditCardSequenceNumber = value;
	}

	/**
	 * Gets the value of the inCreditCardAccountNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCreditCardAccountNumber()
	{
		return inCreditCardAccountNumber;
	}

	/**
	 * Sets the value of the inCreditCardAccountNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCreditCardAccountNumber(final JAXBElement<String> value)
	{
		this.inCreditCardAccountNumber = value;
	}

	/**
	 * Gets the value of the inCreditCardExpirationCard property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCreditCardExpirationCard()
	{
		return inCreditCardExpirationCard;
	}

	/**
	 * Sets the value of the inCreditCardExpirationCard property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCreditCardExpirationCard(final JAXBElement<String> value)
	{
		this.inCreditCardExpirationCard = value;
	}

	/**
	 * Gets the value of the inCreditCardType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInCreditCardType()
	{
		return inCreditCardType;
	}

	/**
	 * Sets the value of the inCreditCardType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInCreditCardType(final JAXBElement<String> value)
	{
		this.inCreditCardType = value;
	}

	/**
	 * Gets the value of the inDataLineItem property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the inDataLineItem property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInDataLineItem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link InDataLineItem }
	 * 
	 * 
	 */
	public List<InDataLineItem> getInDataLineItem()
	{
		if (inDataLineItem == null)
		{
			inDataLineItem = new ArrayList<InDataLineItem>();
		}
		return this.inDataLineItem;
	}

}
