//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:40:46 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btbepic_in2903_ordercreate_hybris_source_v1_webservices.createorder_ws;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for outDataHeader complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outDataHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outSAPResponseMessage" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}outSAPResponseMessage" maxOccurs="unbounded"/>
 *         &lt;element name="out_SalesOrderNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrderNumber" minOccurs="0"/>
 *         &lt;element name="out_orderReasonCode" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_orderReasonCode" minOccurs="0"/>
 *         &lt;element name="out_RiskCategory" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_RiskCategory" minOccurs="0"/>
 *         &lt;element name="out_SalesOrdertTotalNetValue" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrdertTotalNetValue" minOccurs="0"/>
 *         &lt;element name="out_SalesOrderOverallStatus" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrderOverallStatus" minOccurs="0"/>
 *         &lt;element name="out_SalesOrderRejectionStatus" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrderRejectionStatus" minOccurs="0"/>
 *         &lt;element name="out_SalesOrderCompleteness" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrderCompleteness" minOccurs="0"/>
 *         &lt;element name="out_SalesOrderCreditStatus" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_SalesOrderCreditStatus" minOccurs="0"/>
 *         &lt;element name="out_BillingDeliveryBlock" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_BillingDeliveryBlock" minOccurs="0"/>
 *         &lt;element name="outDataLineItem" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}outDataLineItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outDataHeader", propOrder =
{ "outSAPResponseMessage", "outSalesOrderNumber", "outOrderReasonCode", "outRiskCategory", "outSalesOrdertTotalNetValue",
		"outSalesOrderOverallStatus", "outSalesOrderRejectionStatus", "outSalesOrderCompleteness", "outSalesOrderCreditStatus",
		"outBillingDeliveryBlock", "outDataLineItem" })
@XmlRootElement(name = "OutDataHeader")
public class OutDataHeader
{

	@XmlElement(required = true, nillable = true)
	protected List<OutSAPResponseMessage> outSAPResponseMessage;
	@XmlElementRef(name = "out_SalesOrderNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrderNumber;
	@XmlElementRef(name = "out_orderReasonCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outOrderReasonCode;
	@XmlElementRef(name = "out_RiskCategory", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outRiskCategory;
	@XmlElementRef(name = "out_SalesOrdertTotalNetValue", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrdertTotalNetValue;
	@XmlElementRef(name = "out_SalesOrderOverallStatus", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrderOverallStatus;
	@XmlElementRef(name = "out_SalesOrderRejectionStatus", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrderRejectionStatus;
	@XmlElementRef(name = "out_SalesOrderCompleteness", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrderCompleteness;
	@XmlElementRef(name = "out_SalesOrderCreditStatus", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outSalesOrderCreditStatus;
	@XmlElementRef(name = "out_BillingDeliveryBlock", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outBillingDeliveryBlock;
	@XmlElement(required = true, nillable = true)
	protected List<OutDataLineItem> outDataLineItem;

	/**
	 * Gets the value of the outSAPResponseMessage property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the outSAPResponseMessage property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOutSAPResponseMessage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OutSAPResponseMessage }
	 * 
	 * 
	 */
	public List<OutSAPResponseMessage> getOutSAPResponseMessage()
	{
		if (outSAPResponseMessage == null)
		{
			outSAPResponseMessage = new ArrayList<OutSAPResponseMessage>();
		}
		return this.outSAPResponseMessage;
	}

	/**
	 * Gets the value of the outSalesOrderNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrderNumber()
	{
		return outSalesOrderNumber;
	}

	/**
	 * Sets the value of the outSalesOrderNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrderNumber(final JAXBElement<String> value)
	{
		this.outSalesOrderNumber = value;
	}

	/**
	 * Gets the value of the outOrderReasonCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutOrderReasonCode()
	{
		return outOrderReasonCode;
	}

	/**
	 * Sets the value of the outOrderReasonCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutOrderReasonCode(final JAXBElement<String> value)
	{
		this.outOrderReasonCode = value;
	}

	/**
	 * Gets the value of the outRiskCategory property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutRiskCategory()
	{
		return outRiskCategory;
	}

	/**
	 * Sets the value of the outRiskCategory property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutRiskCategory(final JAXBElement<String> value)
	{
		this.outRiskCategory = value;
	}

	/**
	 * Gets the value of the outSalesOrdertTotalNetValue property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrdertTotalNetValue()
	{
		return outSalesOrdertTotalNetValue;
	}

	/**
	 * Sets the value of the outSalesOrdertTotalNetValue property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrdertTotalNetValue(final JAXBElement<String> value)
	{
		this.outSalesOrdertTotalNetValue = value;
	}

	/**
	 * Gets the value of the outSalesOrderOverallStatus property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrderOverallStatus()
	{
		return outSalesOrderOverallStatus;
	}

	/**
	 * Sets the value of the outSalesOrderOverallStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrderOverallStatus(final JAXBElement<String> value)
	{
		this.outSalesOrderOverallStatus = value;
	}

	/**
	 * Gets the value of the outSalesOrderRejectionStatus property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrderRejectionStatus()
	{
		return outSalesOrderRejectionStatus;
	}

	/**
	 * Sets the value of the outSalesOrderRejectionStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrderRejectionStatus(final JAXBElement<String> value)
	{
		this.outSalesOrderRejectionStatus = value;
	}

	/**
	 * Gets the value of the outSalesOrderCompleteness property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrderCompleteness()
	{
		return outSalesOrderCompleteness;
	}

	/**
	 * Sets the value of the outSalesOrderCompleteness property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrderCompleteness(final JAXBElement<String> value)
	{
		this.outSalesOrderCompleteness = value;
	}

	/**
	 * Gets the value of the outSalesOrderCreditStatus property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutSalesOrderCreditStatus()
	{
		return outSalesOrderCreditStatus;
	}

	/**
	 * Sets the value of the outSalesOrderCreditStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutSalesOrderCreditStatus(final JAXBElement<String> value)
	{
		this.outSalesOrderCreditStatus = value;
	}

	/**
	 * Gets the value of the outBillingDeliveryBlock property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutBillingDeliveryBlock()
	{
		return outBillingDeliveryBlock;
	}

	/**
	 * Sets the value of the outBillingDeliveryBlock property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutBillingDeliveryBlock(final JAXBElement<String> value)
	{
		this.outBillingDeliveryBlock = value;
	}

	/**
	 * Gets the value of the outDataLineItem property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the outDataLineItem property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOutDataLineItem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link OutDataLineItem }
	 * 
	 * 
	 */
	public List<OutDataLineItem> getOutDataLineItem()
	{
		if (outDataLineItem == null)
		{
			outDataLineItem = new ArrayList<OutDataLineItem>();
		}
		return this.outDataLineItem;
	}

}
