//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:40:46 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btbepic_in2903_ordercreate_hybris_source_v1_webservices.createorder_ws;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for outResponseData complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outResponseData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outWMResponse" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}outWMResponse"/>
 *         &lt;element name="outDataHeader" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}outDataHeader" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outResponseData", propOrder =
{ "outWMResponse", "outDataHeader" })
@XmlRootElement(name = "OutResponseData")
public class OutResponseData
{

	@XmlElement(required = true)
	protected OutWMResponse outWMResponse;
	@XmlElementRef(name = "outDataHeader", type = JAXBElement.class, required = false)
	protected JAXBElement<OutDataHeader> outDataHeader;

	/**
	 * Gets the value of the outWMResponse property.
	 * 
	 * @return possible object is {@link OutWMResponse }
	 * 
	 */
	public OutWMResponse getOutWMResponse()
	{
		return outWMResponse;
	}

	/**
	 * Sets the value of the outWMResponse property.
	 * 
	 * @param value
	 *           allowed object is {@link OutWMResponse }
	 * 
	 */
	public void setOutWMResponse(final OutWMResponse value)
	{
		this.outWMResponse = value;
	}

	/**
	 * Gets the value of the outDataHeader property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link OutDataHeader }{@code >}
	 * 
	 */
	public JAXBElement<OutDataHeader> getOutDataHeader()
	{
		return outDataHeader;
	}

	/**
	 * Sets the value of the outDataHeader property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link OutDataHeader }{@code >}
	 * 
	 */
	public void setOutDataHeader(final JAXBElement<OutDataHeader> value)
	{
		this.outDataHeader = value;
	}

}
