//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:40:46 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btbepic_in2903_ordercreate_hybris_source_v1_webservices.createorder_ws;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for outScheduleLineItem complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outScheduleLineItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="out_ScheduledLineNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_ScheduledLineNumber" minOccurs="0"/>
 *         &lt;element name="out_LineNumber" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_LineNumber2" minOccurs="0"/>
 *         &lt;element name="out_DeliveryDate" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_DeliveryDate" minOccurs="0"/>
 *         &lt;element name="out_RoundedQuantity" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_RoundedQuantity" minOccurs="0"/>
 *         &lt;element name="out_ConfirmedQuantity" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_ConfirmedQuantity" minOccurs="0"/>
 *         &lt;element name="out_MaterialAvailabilityDate" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_MaterialAvailabilityDate" minOccurs="0"/>
 *         &lt;element name="out_ShipDate" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_ShipDate" minOccurs="0"/>
 *         &lt;element name="out_LineStatus" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_LineStatus" minOccurs="0"/>
 *         &lt;element name="out_LineDeliveryBlock" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_LineDeliveryBlock" minOccurs="0"/>
 *         &lt;element name="out_LineOverallStatus" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}out_LineOverallStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outScheduleLineItem", propOrder =
{ "outScheduledLineNumber", "outLineNumber", "outDeliveryDate", "outRoundedQuantity", "outConfirmedQuantity",
		"outMaterialAvailabilityDate", "outShipDate", "outLineStatus", "outLineDeliveryBlock", "outLineOverallStatus" })
@XmlRootElement(name = "OutScheduleLineItem")
public class OutScheduleLineItem
{

	@XmlElementRef(name = "out_ScheduledLineNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outScheduledLineNumber;
	@XmlElementRef(name = "out_LineNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outLineNumber;
	@XmlElementRef(name = "out_DeliveryDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outDeliveryDate;
	@XmlElementRef(name = "out_RoundedQuantity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outRoundedQuantity;
	@XmlElementRef(name = "out_ConfirmedQuantity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outConfirmedQuantity;
	@XmlElementRef(name = "out_MaterialAvailabilityDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outMaterialAvailabilityDate;
	@XmlElementRef(name = "out_ShipDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outShipDate;
	@XmlElementRef(name = "out_LineStatus", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outLineStatus;
	@XmlElementRef(name = "out_LineDeliveryBlock", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outLineDeliveryBlock;
	@XmlElementRef(name = "out_LineOverallStatus", type = JAXBElement.class, required = false)
	protected JAXBElement<String> outLineOverallStatus;

	/**
	 * Gets the value of the outScheduledLineNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutScheduledLineNumber()
	{
		return outScheduledLineNumber;
	}

	/**
	 * Sets the value of the outScheduledLineNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutScheduledLineNumber(final JAXBElement<String> value)
	{
		this.outScheduledLineNumber = value;
	}

	/**
	 * Gets the value of the outLineNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutLineNumber()
	{
		return outLineNumber;
	}

	/**
	 * Sets the value of the outLineNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutLineNumber(final JAXBElement<String> value)
	{
		this.outLineNumber = value;
	}

	/**
	 * Gets the value of the outDeliveryDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutDeliveryDate()
	{
		return outDeliveryDate;
	}

	/**
	 * Sets the value of the outDeliveryDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutDeliveryDate(final JAXBElement<String> value)
	{
		this.outDeliveryDate = value;
	}

	/**
	 * Gets the value of the outRoundedQuantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutRoundedQuantity()
	{
		return outRoundedQuantity;
	}

	/**
	 * Sets the value of the outRoundedQuantity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutRoundedQuantity(final JAXBElement<String> value)
	{
		this.outRoundedQuantity = value;
	}

	/**
	 * Gets the value of the outConfirmedQuantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutConfirmedQuantity()
	{
		return outConfirmedQuantity;
	}

	/**
	 * Sets the value of the outConfirmedQuantity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutConfirmedQuantity(final JAXBElement<String> value)
	{
		this.outConfirmedQuantity = value;
	}

	/**
	 * Gets the value of the outMaterialAvailabilityDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutMaterialAvailabilityDate()
	{
		return outMaterialAvailabilityDate;
	}

	/**
	 * Sets the value of the outMaterialAvailabilityDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutMaterialAvailabilityDate(final JAXBElement<String> value)
	{
		this.outMaterialAvailabilityDate = value;
	}

	/**
	 * Gets the value of the outShipDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutShipDate()
	{
		return outShipDate;
	}

	/**
	 * Sets the value of the outShipDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutShipDate(final JAXBElement<String> value)
	{
		this.outShipDate = value;
	}

	/**
	 * Gets the value of the outLineStatus property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutLineStatus()
	{
		return outLineStatus;
	}

	/**
	 * Sets the value of the outLineStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutLineStatus(final JAXBElement<String> value)
	{
		this.outLineStatus = value;
	}

	/**
	 * Gets the value of the outLineDeliveryBlock property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutLineDeliveryBlock()
	{
		return outLineDeliveryBlock;
	}

	/**
	 * Sets the value of the outLineDeliveryBlock property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutLineDeliveryBlock(final JAXBElement<String> value)
	{
		this.outLineDeliveryBlock = value;
	}

	/**
	 * Gets the value of the outLineOverallStatus property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOutLineOverallStatus()
	{
		return outLineOverallStatus;
	}

	/**
	 * Sets the value of the outLineOverallStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOutLineOverallStatus(final JAXBElement<String> value)
	{
		this.outLineOverallStatus = value;
	}

}
