//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 08:40:46 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btbepic_in2903_ordercreate_hybris_source_v1_webservices.createorder_ws;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for outSAPResponseMessage complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outSAPResponseMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Return_message_type" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}Return_message_type" minOccurs="0"/>
 *         &lt;element name="Return_message_id" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}Return_message_id" minOccurs="0"/>
 *         &lt;element name="Return_message" type="{http://itsusmpl00082.jnj.com/SG910_BtBEPIC_IN2903_OrderCreate_HYBRIS_Source_v1.webservices:createOrder_WS}Return_message" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outSAPResponseMessage", propOrder =
{ "returnMessageType", "returnMessageId", "returnMessage" })
@XmlRootElement(name = "OutSAPResponseMessage")
public class OutSAPResponseMessage
{

	@XmlElementRef(name = "Return_message_type", type = JAXBElement.class, required = false)
	protected JAXBElement<String> returnMessageType;
	@XmlElementRef(name = "Return_message_id", type = JAXBElement.class, required = false)
	protected JAXBElement<String> returnMessageId;
	@XmlElementRef(name = "Return_message", type = JAXBElement.class, required = false)
	protected JAXBElement<String> returnMessage;

	/**
	 * Gets the value of the returnMessageType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getReturnMessageType()
	{
		return returnMessageType;
	}

	/**
	 * Sets the value of the returnMessageType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setReturnMessageType(final JAXBElement<String> value)
	{
		this.returnMessageType = value;
	}

	/**
	 * Gets the value of the returnMessageId property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getReturnMessageId()
	{
		return returnMessageId;
	}

	/**
	 * Sets the value of the returnMessageId property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setReturnMessageId(final JAXBElement<String> value)
	{
		this.returnMessageId = value;
	}

	/**
	 * Gets the value of the returnMessage property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getReturnMessage()
	{
		return returnMessage;
	}

	/**
	 * Sets the value of the returnMessage property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setReturnMessage(final JAXBElement<String> value)
	{
		this.returnMessage = value;
	}

}
