/**
 *
 */
package com.jnj.gt.mapper.ordertemplate;

import de.hybris.platform.servicelayer.exceptions.ModelLoadingException;
import de.hybris.platform.servicelayer.exceptions.ModelNotFoundException;
import de.hybris.platform.servicelayer.exceptions.ModelSavingException;
import de.hybris.platform.servicelayer.exceptions.UnknownIdentifierException;
import de.hybris.platform.servicelayer.keygenerator.KeyGenerator;
import de.hybris.platform.servicelayer.model.ModelService;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import jakarta.annotation.Resource;

import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;

import com.jnj.core.enums.RecordStatus;
import com.jnj.core.enums.ShareStatus;
import com.jnj.core.model.JnJB2BUnitModel;
import com.jnj.core.model.JnJB2bCustomerModel;
import com.jnj.core.model.JnJProductModel;
import com.jnj.core.model.JnjGTVariantProductModel;
import com.jnj.core.model.JnjOrderTemplateModel;
import com.jnj.core.model.JnjTemplateEntryModel;
import com.jnj.core.util.JnJCommonUtil;
import com.jnj.gt.constants.Jnjgtb2binboundserviceConstants;
import com.jnj.gt.constants.Jnjgtb2binboundserviceConstants.Logging;
import com.jnj.core.services.JnJGTProductService;
import com.jnj.gt.mapper.JnjAbstractMapper;
import com.jnj.gt.model.JnjGTIntOrderTemplateEntryModel;
import com.jnj.gt.model.JnjGTIntOrderTemplateModel;
import com.jnj.core.services.Ordertemplate.JnjGTOrderTemplateService;
import com.jnj.core.services.b2bunit.JnjGTB2BUnitService;
import com.jnj.gt.service.common.JnjGTFeedService;
import com.jnj.core.services.customer.JnjGTCustomerService;
import com.jnj.gt.service.ordertemplate.JnjGTOrderTemplateFeedService;
import com.jnj.gt.util.JnjGTInboundUtil;



/**
 * @author sakshi.kashiva
 *
 */
public class JnjGTOrderTemplateDataLoadMapper extends JnjAbstractMapper
{
	private static final Logger LOGGER = Logger.getLogger(JnjGTOrderTemplateDataLoadMapper.class);

	@Autowired
	private JnjGTFeedService jnjGTFeedService;

	@Autowired
	private JnjGTOrderTemplateService jnjGTOrderTemplateService;

	@Resource(name = "GTCustomerService")
	private JnjGTCustomerService jnjGTCustomerService;

	@Autowired
	private JnjGTB2BUnitService jnjGTB2BUnitService;

	@Autowired
	ModelService modelService;

	@Autowired
	private KeyGenerator guidKeyGenerator;

	@Resource(name = "productService")
	JnJGTProductService jnJGTProductService;

	@Autowired
	private JnjGTOrderTemplateFeedService jnjGTOrderTemplateFeedService;

	@Override
	public void processIntermediateRecords()
	{
		mapOrderTemplateDataToHybris();

	}

	/**
	 * Map order Template. Mapping the intermediate records in hybris model
	 *
	 * @return the save status
	 */
	public boolean mapOrderTemplateDataToHybris()
	{
		if (LOGGER.isDebugEnabled())
		{
			LOGGER.debug("mapOrderTemplateDataToHybris()" + Logging.HYPHEN + Logging.BEGIN_OF_METHOD + Logging.HYPHEN
					+ Logging.START_TIME + JnJCommonUtil.getCurrentDateTime());
		}
		//Fetching the records from intermediate table with pending status
		final Collection<JnjGTIntOrderTemplateModel> jnjIntOrderModelList = (Collection<JnjGTIntOrderTemplateModel>) jnjGTFeedService
				.getRecordsByStatus(JnjGTIntOrderTemplateModel._TYPECODE, RecordStatus.PENDING);


		JnjOrderTemplateModel JnjOrderTemplateModel = null;
		String errorMessage = null;
		boolean recordStatus = false;
		if (CollectionUtils.isNotEmpty(jnjIntOrderModelList))
		{
			for (final JnjGTIntOrderTemplateModel jnjGTIntOrderTemplateModel : jnjIntOrderModelList)
			{
				recordStatus = false;
				try
				{
					final JnjOrderTemplateModel order = new JnjOrderTemplateModel();
					JnJB2bCustomerModel customer = null;
					order.setTemplateNumber(jnjGTIntOrderTemplateModel.getId());
					customer = getCustomerForTemplate(jnjGTIntOrderTemplateModel);
					JnJB2BUnitModel b2bUnit = null;
					b2bUnit = getB2bUnitForTemplate(jnjGTIntOrderTemplateModel);

					//Fetching the records from intermediate table with pending status
					final Collection<JnjGTIntOrderTemplateEntryModel> jnjIntOrderEntryModelList = jnjGTOrderTemplateFeedService
							.getJnjGTIntOrderTemplateEntry(jnjGTIntOrderTemplateModel.getId());

					//Creating A Template Only When the Customer Exist and Entry Exist
					if (customer != null && CollectionUtils.isNotEmpty(jnjIntOrderEntryModelList))
					{
						//Fetching the order template model
						JnjOrderTemplateModel = jnjGTOrderTemplateService.getJnjGTOrderTemplateModel(order);
						//Validating if the model is created
						if (null == JnjOrderTemplateModel)
						{
							JnjOrderTemplateModel = modelService.create(JnjOrderTemplateModel.class);
							//Setting the Template Code To AutoGenerated Id
							JnjOrderTemplateModel.setCode(guidKeyGenerator.generate().toString());
						}
						//Setting the Template Number  To Id From The Intermediate Table.
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getId()))
						{
							JnjOrderTemplateModel.setTemplateNumber(jnjGTIntOrderTemplateModel.getId());
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getName()))
						{
							JnjOrderTemplateModel.setName(jnjGTIntOrderTemplateModel.getName());
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getOrderType()))
						{
							JnjOrderTemplateModel.setOrderType(jnjGTIntOrderTemplateModel.getOrderType());
						}

						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getBuisnessSector()))
						{
							JnjOrderTemplateModel.setBuisnessSector(jnjGTIntOrderTemplateModel.getBuisnessSector());
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getSource()))
						{
							JnjOrderTemplateModel.setSource(JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateModel
									.getSource()));
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateModel.getShipToId()))
						{
							JnjOrderTemplateModel.setAddressId(jnjGTIntOrderTemplateModel.getShipToId());
						}
						JnjOrderTemplateModel.setAuthor(customer);
						if (null != jnjGTIntOrderTemplateModel.getRecTimeStamp())
						{
							JnjOrderTemplateModel.setRecTimeStamp(jnjGTIntOrderTemplateModel.getRecTimeStamp());
						}
						JnjOrderTemplateModel.setUnit(b2bUnit);
						if (null != (jnjGTIntOrderTemplateModel.getShareStatus()))
						{
							if (jnjGTIntOrderTemplateModel.getShareStatus().equals(
									Jnjgtb2binboundserviceConstants.UserProfile.PRIVATE_STATUS_CODE))
							{
								JnjOrderTemplateModel.setShareStatus(ShareStatus.PRIVATE);
								JnjOrderTemplateModel.setVisibleTo(customer);
							}
							else
							{
								JnjOrderTemplateModel.setShareStatus(ShareStatus.SHARED);
								if (null != b2bUnit)
								{
									JnjOrderTemplateModel.setVisibleTo(b2bUnit);
								}
								else
								{
									JnjOrderTemplateModel.setShareStatus(ShareStatus.PRIVATE);
									JnjOrderTemplateModel.setVisibleTo(customer);
								}

							}
						}
						recordStatus = mapOrderTemplateEntryToHybris(jnjIntOrderEntryModelList, JnjOrderTemplateModel, recordStatus);
					}

					else
					{
						if (customer == null)
						{
							logErrorForCustomerNotFound(recordStatus, jnjGTIntOrderTemplateModel);
							errorMessage = "Order Template Note Created For Template Order '" + jnjGTIntOrderTemplateModel.getId()
									+ "' As Customer Not Found For Template";
						}
						else
						{
							LOGGER.error("Order Template Note Created For Template Order '" + jnjGTIntOrderTemplateModel.getId()
									+ "' For Zero Order Lines");
							errorMessage = "Order Template Note Created For Template Order '" + jnjGTIntOrderTemplateModel.getId()
									+ "' For Zero Order Lines";
						}
						setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
						recordStatus = false;
					}
				}
				catch (final UnknownIdentifierException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateDataToHybris()" + Logging.HYPHEN
							+ "Unknown Identifier Exception occurred -" + exception.getMessage(), exception);
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					errorMessage = exception.getMessage();
				}
				catch (final ModelNotFoundException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateDataToHybris()" + Logging.HYPHEN
							+ "Model Not Found Exception occurred -" + exception.getMessage(), exception);
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					errorMessage = exception.getMessage();
				}
				catch (final ModelLoadingException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "Model Not Found Exception occurred -" + exception.getMessage(), exception);
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					errorMessage = exception.getMessage();
				}
				catch (final ModelSavingException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateDataToHybris()" + Logging.HYPHEN
							+ "MOdel Saving Exception occurred -" + exception.getMessage(), exception);
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					errorMessage = exception.getMessage();
				}
				catch (final Exception exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateDataToHybris()" + Logging.HYPHEN
							+ "Thwoable Exception occurred -" + exception.getMessage(), exception);
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					errorMessage = exception.getMessage();
				}
				if (recordStatus)
				{
					//Record Successfully saved to Hybris. Changing the status to 'Success'.
					if (LOGGER.isDebugEnabled())
					{
						LOGGER.debug(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateDataToHybris()" + Logging.HYPHEN
								+ "The Record with Order ID: " + jnjGTIntOrderTemplateModel.getId()
								+ " processed successfully. Changing the Record status to 'SUCCESS'");
					}
					jnjGTFeedService.updateIntermediateRecord(jnjGTIntOrderTemplateModel, RecordStatus.SUCCESS, false, null);
				}
				else
				{
					//Update the Write Dash Board and Updating the Status of Record to "Error" if the Retry Threshold is reached.
					jnjGTFeedService.updateIntermediateRecord(jnjGTIntOrderTemplateModel, null, true, errorMessage,
							Logging.ORDER_TEMPLATE_FEED, jnjGTIntOrderTemplateModel.getEmail());
					setAllOrderLinesForOrderToError(errorMessage, jnjGTIntOrderTemplateModel);
					LOGGER.info(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapUserDataToHybris()" + Logging.HYPHEN
							+ "The Record with Order ID: " + jnjGTIntOrderTemplateModel.getId() + " was not processed successfully.");
				}
			}
		}
		return recordStatus;
	}

	/**
	 * @param errorMessage
	 * @param jnjGTIntOrderTemplateModel
	 * @return
	 */
	private void setAllOrderLinesForOrderToError(String errorMessage, final JnjGTIntOrderTemplateModel jnjGTIntOrderTemplateModel)
	{
		final Collection<JnjGTIntOrderTemplateEntryModel> jnjIntOrderEntryModelListToError = jnjGTOrderTemplateFeedService
				.getJnjGTIntOrderTemplateEntry(jnjGTIntOrderTemplateModel.getId());
		for (final JnjGTIntOrderTemplateEntryModel jnjGTIntOrderTemplateEntryModel : jnjIntOrderEntryModelListToError)
		{
			errorMessage = "Line Id '" + jnjGTIntOrderTemplateEntryModel.getLineid() + " Is Not Error Out";
			jnjGTFeedService.updateIntermediateRecord(jnjGTIntOrderTemplateEntryModel, null, true, errorMessage,
					Logging.ORDER_TEMPLATE_FEED, String.valueOf(jnjGTIntOrderTemplateEntryModel.getLineid()));
		}
	}

	/**
	 * @param recordStatus
	 * @param jnjGTIntOrderTemplateModel
	 * @return
	 */
	private void logErrorForCustomerNotFound(final boolean recordStatus,
			final JnjGTIntOrderTemplateModel jnjGTIntOrderTemplateModel)
	{
		final String sourceSystemId = JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateModel.getSource());
		if (null != sourceSystemId && sourceSystemId.equals(Jnjgtb2binboundserviceConstants.Product.MDD_SRC_SYS)
				&& null != jnjGTIntOrderTemplateModel.getUserId())
		{
			LOGGER.error("Order Template Model '" + jnjGTIntOrderTemplateModel.getId()
					+ "' Not Created Because Customer Not Found With User Id: '" + jnjGTIntOrderTemplateModel.getUserId()
					+ "' In Hybris For Source" + sourceSystemId);
		}
		else if (null != sourceSystemId && sourceSystemId.equals(Jnjgtb2binboundserviceConstants.Product.CONSUMER_SRC_SYS)
				&& null != jnjGTIntOrderTemplateModel.getEmail())
		{
			LOGGER.error("Order Template Model '" + jnjGTIntOrderTemplateModel.getId()
					+ "' Not Created Because Not Found With Email Id: '" + jnjGTIntOrderTemplateModel.getEmail()
					+ "' In Hybris For Source" + sourceSystemId);
		}
		else if (null != sourceSystemId && sourceSystemId.equals(Jnjgtb2binboundserviceConstants.Product.MDD_SRC_SYS)
				&& null == jnjGTIntOrderTemplateModel.getUserId())
		{
			LOGGER.error("Order Template Model '" + jnjGTIntOrderTemplateModel.getId() + "' Not Created Because Of Empty UserId");
		}
		else if (null != sourceSystemId && sourceSystemId.equals(Jnjgtb2binboundserviceConstants.Product.CONSUMER_SRC_SYS)
				&& null == jnjGTIntOrderTemplateModel.getEmail())
		{
			LOGGER.error("Order Template Model '" + jnjGTIntOrderTemplateModel.getId() + "' Not Created Because Of Empty Email");
		}

	}

	/**
	 * @param jnjGTIntOrderTemplateModel
	 */
	private JnJB2BUnitModel getB2bUnitForTemplate(final JnjGTIntOrderTemplateModel jnjGTIntOrderTemplateModel)
	{
		JnJB2BUnitModel JnJB2BUnitModel = null;
		final String srcSysID = JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateModel.getSource());
		if (srcSysID != null && srcSysID.equals(Jnjgtb2binboundserviceConstants.Product.MDD_SRC_SYS)
				&& null != jnjGTIntOrderTemplateModel.getShipToId())
		{
			JnJB2BUnitModel = jnjGTB2BUnitService.getB2BUnitModelForUid(jnjGTIntOrderTemplateModel.getShipToId(), srcSysID);
		}
		else if (srcSysID != null && null != jnjGTIntOrderTemplateModel.getSoldToId())
		{
			JnJB2BUnitModel = jnjGTB2BUnitService.getB2BUnitModelForUid(jnjGTIntOrderTemplateModel.getSoldToId(), srcSysID);
		}
		return JnJB2BUnitModel;
	}

	/**
	 * @param jnjGTIntOrderTemplateModel
	 */
	private JnJB2bCustomerModel getCustomerForTemplate(final JnjGTIntOrderTemplateModel jnjGTIntOrderTemplateModel)
	{
		JnJB2bCustomerModel customer = null;
		final String srcSysID = JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateModel.getSource());
		if (null != srcSysID && srcSysID.equals(Jnjgtb2binboundserviceConstants.Product.MDD_SRC_SYS)
				&& null != jnjGTIntOrderTemplateModel.getUserId())
		{
			customer = new JnJB2bCustomerModel();
			customer.setGatewayUserId(jnjGTIntOrderTemplateModel.getUserId());
			customer = jnjGTCustomerService.getJnJB2bCustomerModel(customer);
		}
		else if (null != srcSysID && srcSysID.equals(Jnjgtb2binboundserviceConstants.Product.CONSUMER_SRC_SYS)
				&& null != jnjGTIntOrderTemplateModel.getEmail())
		{
			customer = new JnJB2bCustomerModel();
			customer.setEmail(jnjGTIntOrderTemplateModel.getEmail());
			customer = jnjGTCustomerService.getJnJB2bCustomerModel(customer);
		}
		return customer;
	}

	/**
	 * Map order Template Entry. Mapping the intermediate records of entry in hybris model
	 *
	 * @param recordStatus2
	 *
	 * @return the save status
	 */

	public boolean mapOrderTemplateEntryToHybris(final Collection<JnjGTIntOrderTemplateEntryModel> jnjIntOrderEntryModelList,
			JnjOrderTemplateModel JnjOrderTemplateModel, boolean recordStatusForOrderTemplate)
	{

		if (LOGGER.isDebugEnabled())
		{
			LOGGER.debug("mapOrderTemplateEntryToHybris()" + Logging.HYPHEN + Logging.BEGIN_OF_METHOD + Logging.HYPHEN
					+ Logging.START_TIME + JnJCommonUtil.getCurrentDateTime());
		}


		String errorMessage = null;
		boolean recordStatus = false;
		{
			for (final JnjGTIntOrderTemplateEntryModel jnjGTIntOrderTemplateEntryModel : jnjIntOrderEntryModelList)
			{
				recordStatus = false;
				try
				{
					//Get the actual Product From the Respective Online Catalog Versions
					final JnJProductModel product = jnJGTProductService.getProductForOrderTemplate(
							jnjGTIntOrderTemplateEntryModel.getProduct(),
							JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateEntryModel.getSource()));
					//Validating if the model is created
					if (JnjOrderTemplateModel != null && product != null)
					{
						jnjGTOrderTemplateService.saveTemplate(JnjOrderTemplateModel);
						JnjTemplateEntryModel JnjTemplateEntryModel = new JnjTemplateEntryModel();
						JnjTemplateEntryModel.setOrderTemplate(JnjOrderTemplateModel);
						JnjTemplateEntryModel.setOrderLineId(String.valueOf(jnjGTIntOrderTemplateEntryModel.getOrderLineId()));
						JnjTemplateEntryModel = jnjGTOrderTemplateService.getJnjGTOrderTemplateEntryModel(JnjTemplateEntryModel);
						if (null == JnjTemplateEntryModel)
						{
							JnjTemplateEntryModel = modelService.create(JnjTemplateEntryModel.class);
						}
						if (null != (jnjGTIntOrderTemplateEntryModel.getOrderId()))
						{
							JnjTemplateEntryModel.setOrderTemplate(JnjOrderTemplateModel);
						}
						if (null != (jnjGTIntOrderTemplateEntryModel.getRecTimeStamp()))
						{
							JnjTemplateEntryModel.setRecTimeStamp(jnjGTIntOrderTemplateEntryModel.getRecTimeStamp());
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateEntryModel.getBuisnessSector()))
						{
							JnjTemplateEntryModel.setBuisnessSector(jnjGTIntOrderTemplateEntryModel.getBuisnessSector());
						}
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateEntryModel.getSource()))
						{
							JnjTemplateEntryModel.setSource(JnjGTInboundUtil.fetchValidSourceSysId(jnjGTIntOrderTemplateEntryModel
									.getSource()));
						}

						//Get the materialBaseProduct Product
						final JnJProductModel materialBaseProduct = product.getMaterialBaseProduct();
						JnjGTVariantProductModel jnjGTVariantProductModel = null;
						//Check whether the materialBaseProduct Is Not null
						if (materialBaseProduct != null)
						{
							//Set the Product In Order Template  as MaterialBaseProduct
							JnjTemplateEntryModel.setProduct(materialBaseProduct);
							//Get the Variant From the Base Product
							jnjGTVariantProductModel = jnJGTProductService.getDeliveryGTIN(materialBaseProduct);
						}
						else
						{
							//Set the Product In Order Template  as Product
							JnjTemplateEntryModel.setProduct(product);
							//Get the Variant From the  Product
							jnjGTVariantProductModel = jnJGTProductService.getDeliveryGTIN(product);
						}
						//Set the Respective Variant Product
						JnjTemplateEntryModel.setReferencedVariant(jnjGTVariantProductModel);
						if (StringUtils.isNotEmpty(jnjGTIntOrderTemplateEntryModel.getQuantity()))
						{
							JnjTemplateEntryModel.setQty(Long.valueOf(jnjGTIntOrderTemplateEntryModel.getQuantity()).longValue());
						}
						if (null != (jnjGTIntOrderTemplateEntryModel.getOrderLineId()))
						{
							JnjTemplateEntryModel.setOrderLineId(String.valueOf(jnjGTIntOrderTemplateEntryModel.getOrderLineId()));
						}
						recordStatus = jnjGTOrderTemplateService.saveTemplateEntry(JnjTemplateEntryModel);
						if (recordStatus)
						{
							final List<JnjTemplateEntryModel> newentryList = new ArrayList<JnjTemplateEntryModel>();
							for (final JnjTemplateEntryModel jnjOrderTemplateEntryModel : JnjOrderTemplateModel.getEntryList())
							{
								newentryList.add(jnjOrderTemplateEntryModel);
							}
							if (!newentryList.contains(JnjTemplateEntryModel))
							{
								newentryList.add(JnjTemplateEntryModel);
							}
							JnjOrderTemplateModel.setEntryList(newentryList);
							modelService.saveAll(JnjOrderTemplateModel);
							recordStatusForOrderTemplate = true;
							LOGGER.info("Order Template Created'" + JnjOrderTemplateModel.getTemplateNumber() + "'");
						}
						else
						{
							modelService.remove(JnjOrderTemplateModel);
							LOGGER.info("Order Template Deleted For'" + JnjOrderTemplateModel.getTemplateNumber());
							recordStatusForOrderTemplate = false;
						}

					}
					else
					{
						final JnjOrderTemplateModel order = new JnjOrderTemplateModel();
						order.setTemplateNumber(String.valueOf(jnjGTIntOrderTemplateEntryModel.getOrderId()));
						JnjOrderTemplateModel = jnjGTOrderTemplateService.getJnjGTOrderTemplateModel(order);
						if (JnjOrderTemplateModel != null)
						{
							final JnjTemplateEntryModel orderEntry = new JnjTemplateEntryModel();
							orderEntry.setOrderTemplate(order);
							final List<JnjTemplateEntryModel> jnjGTOrderTemplateEntryModelList = jnjGTOrderTemplateService
									.getJnjGTOrderTemplateEntryModelList(orderEntry);
							if (CollectionUtils.isNotEmpty(jnjGTOrderTemplateEntryModelList))
							{
								modelService.removeAll(jnjGTOrderTemplateEntryModelList);
							}
							modelService.remove(order);
						}
						LOGGER.info("Order Template  Not Created Because Of Inavalid Entries'"
								+ jnjGTIntOrderTemplateEntryModel.getOrderId() + "'");
						recordStatusForOrderTemplate = false;
					}
				}
				catch (final UnknownIdentifierException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "Unknown Identifier Exception occurred -" + exception.getMessage(), exception);
					errorMessage = exception.getMessage();
				}
				catch (final ModelNotFoundException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "Model Not Found Exception occurred -" + exception.getMessage(), exception);
					errorMessage = exception.getMessage();
				}
				catch (final ModelLoadingException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "Model Not Found Exception occurred -" + exception.getMessage(), exception);
					errorMessage = exception.getMessage();
				}
				catch (final ModelSavingException exception)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "MOdel Saving Exception occurred -" + exception.getMessage(), exception);
					errorMessage = exception.getMessage();
				}
				catch (final Throwable throwable)
				{
					LOGGER.error(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "Thwoable Exception occurred -" + throwable.getMessage(), throwable);
					errorMessage = throwable.getMessage();
				}

				if (recordStatus)
				{
					//Record Successfully saved to Hybris. Changing the status to 'Success'.
					if (LOGGER.isDebugEnabled())
					{
						LOGGER.debug(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
								+ "The Record with Order ID: " + jnjGTIntOrderTemplateEntryModel.getOrderId() + " With Line Id "
								+ jnjGTIntOrderTemplateEntryModel.getOrderLineId() + " With Product Id "
								+ jnjGTIntOrderTemplateEntryModel.getProduct()
								+ " processed successfully. Changing the Record status to 'SUCCESS'");
					}
					jnjGTFeedService.updateIntermediateRecord(jnjGTIntOrderTemplateEntryModel, RecordStatus.SUCCESS, false, null);
				}
				else
				{
					jnjGTFeedService.updateIntermediateRecord(jnjGTIntOrderTemplateEntryModel, null, true, errorMessage,
							Logging.SALES_ALIGNMENT_FEED, String.valueOf(jnjGTIntOrderTemplateEntryModel.getLineid()));
					LOGGER.info(Logging.ORDER_TEMPLATE_FEED + Logging.HYPHEN + "mapOrderTemplateEntryToHybris()" + Logging.HYPHEN
							+ "The Record with Order ID: " + jnjGTIntOrderTemplateEntryModel.getOrderId() + " With Line Id  "
							+ jnjGTIntOrderTemplateEntryModel.getOrderLineId() + " With Product Id "
							+ jnjGTIntOrderTemplateEntryModel.getProduct() + " was not processed successfully.");
				}
			}

		}
		return recordStatusForOrderTemplate;
	}

	@Override
	public void processIntermediateRecords(String facadeBeanId) {
		// TODO Auto-generated method stub
		
	}
}
