//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for ContactAndAddress complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactAndAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contact" type="{http://fedex.com/ws/track/v8}Contact"/>
 *         &lt;element name="Address" type="{http://fedex.com/ws/track/v8}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactAndAddress", propOrder =
{ "contact", "address" })
@XmlRootElement(name = "ContactAndAddress")
public class ContactAndAddress
{

	@XmlElement(name = "Contact", required = true)
	protected Contact contact;
	@XmlElement(name = "Address")
	protected Address address;

	/**
	 * Gets the value of the contact property.
	 * 
	 * @return possible object is {@link Contact }
	 * 
	 */
	public Contact getContact()
	{
		return contact;
	}

	/**
	 * Sets the value of the contact property.
	 * 
	 * @param value
	 *           allowed object is {@link Contact }
	 * 
	 */
	public void setContact(final Contact value)
	{
		this.contact = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link Address }
	 * 
	 */
	public Address getAddress()
	{
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *           allowed object is {@link Address }
	 * 
	 */
	public void setAddress(final Address value)
	{
		this.address = value;
	}

}
