//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import java.math.BigInteger;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The dimensions of this package and the unit type used for the measurements.
 * 
 * <p>
 * Java class for Dimensions complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dimensions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="Units" type="{http://fedex.com/ws/track/v8}LinearUnits" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dimensions", propOrder =
{ "length", "width", "height", "units" })
@XmlRootElement(name = "Dimensions")
public class Dimensions
{

	@XmlElement(name = "Length")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger length;
	@XmlElement(name = "Width")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger width;
	@XmlElement(name = "Height")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger height;
	@XmlElement(name = "Units")
	protected LinearUnits units;

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getLength()
	{
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *           allowed object is {@link BigInteger }
	 * 
	 */
	public void setLength(final BigInteger value)
	{
		this.length = value;
	}

	/**
	 * Gets the value of the width property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getWidth()
	{
		return width;
	}

	/**
	 * Sets the value of the width property.
	 * 
	 * @param value
	 *           allowed object is {@link BigInteger }
	 * 
	 */
	public void setWidth(final BigInteger value)
	{
		this.width = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *           allowed object is {@link BigInteger }
	 * 
	 */
	public void setHeight(final BigInteger value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the units property.
	 * 
	 * @return possible object is {@link LinearUnits }
	 * 
	 */
	public LinearUnits getUnits()
	{
		return units;
	}

	/**
	 * Sets the value of the units property.
	 * 
	 * @param value
	 *           allowed object is {@link LinearUnits }
	 * 
	 */
	public void setUnits(final LinearUnits value)
	{
		this.units = value;
	}

}
