//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Identifies the representation of human-readable text.
 * 
 * <p>
 * Java class for Localization complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Localization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LanguageCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LocaleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Localization", propOrder =
{ "languageCode", "localeCode" })
@XmlRootElement(name = "Localization")
public class Localization
{

	@XmlElement(name = "LanguageCode", required = true)
	protected String languageCode;
	@XmlElement(name = "LocaleCode")
	protected String localeCode;

	/**
	 * Gets the value of the languageCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLanguageCode()
	{
		return languageCode;
	}

	/**
	 * Sets the value of the languageCode property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setLanguageCode(final String value)
	{
		this.languageCode = value;
	}

	/**
	 * Gets the value of the localeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLocaleCode()
	{
		return localeCode;
	}

	/**
	 * Sets the value of the localeCode property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setLocaleCode(final String value)
	{
		this.localeCode = value;
	}

}
