//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.12 at 09:19:46 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for PackagingType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="PackagingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FEDEX_10KG_BOX"/>
 *     &lt;enumeration value="FEDEX_25KG_BOX"/>
 *     &lt;enumeration value="FEDEX_BOX"/>
 *     &lt;enumeration value="FEDEX_ENVELOPE"/>
 *     &lt;enumeration value="FEDEX_PAK"/>
 *     &lt;enumeration value="FEDEX_TUBE"/>
 *     &lt;enumeration value="YOUR_PACKAGING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PackagingType")
@XmlEnum
@XmlRootElement(name = "PackagingType")
public enum PackagingType
{

	@XmlEnumValue("FEDEX_10KG_BOX")
	FEDEX_10_KG_BOX("FEDEX_10KG_BOX"), @XmlEnumValue("FEDEX_25KG_BOX")
	FEDEX_25_KG_BOX("FEDEX_25KG_BOX"), FEDEX_BOX("FEDEX_BOX"), FEDEX_ENVELOPE("FEDEX_ENVELOPE"), FEDEX_PAK("FEDEX_PAK"), FEDEX_TUBE(
			"FEDEX_TUBE"), YOUR_PACKAGING("YOUR_PACKAGING");
	private final String value;

	PackagingType(final String v)
	{
		value = v;
	}

	public String value()
	{
		return value;
	}

	public static PackagingType fromValue(final String v)
	{
		for (final PackagingType c : PackagingType.values())
		{
			if (c.value.equals(v))
			{
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
