//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.12 at 09:19:46 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://fedex.com/ws/track/v8", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fedex.ws.track.v8;
