//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for SpecialInstructionStatusDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialInstructionStatusDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://fedex.com/ws/track/v8}SpecialInstructionsStatusCode" minOccurs="0"/>
 *         &lt;element name="StatusCreateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialInstructionStatusDetail", propOrder =
{ "status", "statusCreateTime" })
@XmlRootElement(name = "SpecialInstructionStatusDetail")
public class SpecialInstructionStatusDetail
{

	@XmlElement(name = "Status")
	protected SpecialInstructionsStatusCode status;
	@XmlElement(name = "StatusCreateTime")
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar statusCreateTime;

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link SpecialInstructionsStatusCode }
	 * 
	 */
	public SpecialInstructionsStatusCode getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *           allowed object is {@link SpecialInstructionsStatusCode }
	 * 
	 */
	public void setStatus(final SpecialInstructionsStatusCode value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the statusCreateTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getStatusCreateTime()
	{
		return statusCreateTime;
	}

	/**
	 * Sets the value of the statusCreateTime property.
	 * 
	 * @param value
	 *           allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setStatusCreateTime(final XMLGregorianCalendar value)
	{
		this.statusCreateTime = value;
	}

}
