//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The descriptive data returned from a FedEx package tracking request.
 * 
 * <p>
 * Java class for TrackReply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HighestSeverity" type="{http://fedex.com/ws/track/v8}NotificationSeverityType"/>
 *         &lt;element name="Notifications" type="{http://fedex.com/ws/track/v8}Notification" maxOccurs="unbounded"/>
 *         &lt;element name="TransactionDetail" type="{http://fedex.com/ws/track/v8}TransactionDetail" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://fedex.com/ws/track/v8}VersionId"/>
 *         &lt;element name="CompletedTrackDetails" type="{http://fedex.com/ws/track/v8}CompletedTrackDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackReply", propOrder =
{ "highestSeverity", "notifications", "transactionDetail", "version", "completedTrackDetails" })
@XmlRootElement(name = "TrackReply")
public class TrackReply
{

	@XmlElement(name = "HighestSeverity", required = true)
	protected NotificationSeverityType highestSeverity;
	@XmlElement(name = "Notifications", required = true)
	protected List<Notification> notifications;
	@XmlElement(name = "TransactionDetail")
	protected TransactionDetail transactionDetail;
	@XmlElement(name = "Version", required = true)
	protected VersionId version;
	@XmlElement(name = "CompletedTrackDetails")
	protected List<CompletedTrackDetail> completedTrackDetails;

	/**
	 * Gets the value of the highestSeverity property.
	 * 
	 * @return possible object is {@link NotificationSeverityType }
	 * 
	 */
	public NotificationSeverityType getHighestSeverity()
	{
		return highestSeverity;
	}

	/**
	 * Sets the value of the highestSeverity property.
	 * 
	 * @param value
	 *           allowed object is {@link NotificationSeverityType }
	 * 
	 */
	public void setHighestSeverity(final NotificationSeverityType value)
	{
		this.highestSeverity = value;
	}

	/**
	 * Gets the value of the notifications property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the notifications property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNotifications().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Notification }
	 * 
	 * 
	 */
	public List<Notification> getNotifications()
	{
		if (notifications == null)
		{
			notifications = new ArrayList<Notification>();
		}
		return this.notifications;
	}

	/**
	 * Gets the value of the transactionDetail property.
	 * 
	 * @return possible object is {@link TransactionDetail }
	 * 
	 */
	public TransactionDetail getTransactionDetail()
	{
		return transactionDetail;
	}

	/**
	 * Sets the value of the transactionDetail property.
	 * 
	 * @param value
	 *           allowed object is {@link TransactionDetail }
	 * 
	 */
	public void setTransactionDetail(final TransactionDetail value)
	{
		this.transactionDetail = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link VersionId }
	 * 
	 */
	public VersionId getVersion()
	{
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *           allowed object is {@link VersionId }
	 * 
	 */
	public void setVersion(final VersionId value)
	{
		this.version = value;
	}

	/**
	 * Gets the value of the completedTrackDetails property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the completedTrackDetails property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCompletedTrackDetails().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CompletedTrackDetail }
	 * 
	 * 
	 */
	public List<CompletedTrackDetail> getCompletedTrackDetails()
	{
		if (completedTrackDetails == null)
		{
			completedTrackDetails = new ArrayList<CompletedTrackDetail>();
		}
		return this.completedTrackDetails;
	}

}
