//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for TrackPaymentType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="TrackPaymentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CASH_OR_CHECK_AT_DESTINATION"/>
 *     &lt;enumeration value="CASH_OR_CHECK_AT_ORIGIN"/>
 *     &lt;enumeration value="CREDIT_CARD_AT_DESTINATION"/>
 *     &lt;enumeration value="CREDIT_CARD_AT_ORIGIN"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="RECIPIENT_ACCOUNT"/>
 *     &lt;enumeration value="SHIPPER_ACCOUNT"/>
 *     &lt;enumeration value="THIRD_PARTY_ACCOUNT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrackPaymentType")
@XmlEnum
@XmlRootElement(name = "TrackPaymentType")
public enum TrackPaymentType
{

	CASH_OR_CHECK_AT_DESTINATION, CASH_OR_CHECK_AT_ORIGIN, CREDIT_CARD_AT_DESTINATION, CREDIT_CARD_AT_ORIGIN, OTHER, RECIPIENT_ACCOUNT, SHIPPER_ACCOUNT, THIRD_PARTY_ACCOUNT;

	public String value()
	{
		return name();
	}

	public static TrackPaymentType fromValue(final String v)
	{
		return valueOf(v);
	}

}
