//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for TrackOtherIdentifierDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackOtherIdentifierDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageIdentifier" type="{http://fedex.com/ws/track/v8}TrackPackageIdentifier" minOccurs="0"/>
 *         &lt;element name="TrackingNumberUniqueIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CarrierCode" type="{http://fedex.com/ws/track/v8}CarrierCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackOtherIdentifierDetail", propOrder =
{ "packageIdentifier", "trackingNumberUniqueIdentifier", "carrierCode" })
@XmlRootElement(name = "TrackOtherIdentifierDetail")
public class TrackOtherIdentifierDetail
{

	@XmlElement(name = "PackageIdentifier")
	protected TrackPackageIdentifier packageIdentifier;
	@XmlElement(name = "TrackingNumberUniqueIdentifier")
	protected String trackingNumberUniqueIdentifier;
	@XmlElement(name = "CarrierCode")
	protected CarrierCodeType carrierCode;

	/**
	 * Gets the value of the packageIdentifier property.
	 * 
	 * @return possible object is {@link TrackPackageIdentifier }
	 * 
	 */
	public TrackPackageIdentifier getPackageIdentifier()
	{
		return packageIdentifier;
	}

	/**
	 * Sets the value of the packageIdentifier property.
	 * 
	 * @param value
	 *           allowed object is {@link TrackPackageIdentifier }
	 * 
	 */
	public void setPackageIdentifier(final TrackPackageIdentifier value)
	{
		this.packageIdentifier = value;
	}

	/**
	 * Gets the value of the trackingNumberUniqueIdentifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTrackingNumberUniqueIdentifier()
	{
		return trackingNumberUniqueIdentifier;
	}

	/**
	 * Sets the value of the trackingNumberUniqueIdentifier property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setTrackingNumberUniqueIdentifier(final String value)
	{
		this.trackingNumberUniqueIdentifier = value;
	}

	/**
	 * Gets the value of the carrierCode property.
	 * 
	 * @return possible object is {@link CarrierCodeType }
	 * 
	 */
	public CarrierCodeType getCarrierCode()
	{
		return carrierCode;
	}

	/**
	 * Sets the value of the carrierCode property.
	 * 
	 * @param value
	 *           allowed object is {@link CarrierCodeType }
	 * 
	 */
	public void setCarrierCode(final CarrierCodeType value)
	{
		this.carrierCode = value;
	}

}
