//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Descriptive data that governs data payload language/translations. The TransactionDetail from the request is echoed
 * back to the caller in the corresponding reply.
 * 
 * <p>
 * Java class for TransactionDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Localization" type="{http://fedex.com/ws/track/v8}Localization" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDetail", propOrder =
{ "customerTransactionId", "localization" })
@XmlRootElement(name = "TransactionDetail")
public class TransactionDetail
{

	@XmlElement(name = "CustomerTransactionId")
	protected String customerTransactionId;
	@XmlElement(name = "Localization")
	protected Localization localization;

	/**
	 * Gets the value of the customerTransactionId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustomerTransactionId()
	{
		return customerTransactionId;
	}

	/**
	 * Sets the value of the customerTransactionId property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setCustomerTransactionId(final String value)
	{
		this.customerTransactionId = value;
	}

	/**
	 * Gets the value of the localization property.
	 * 
	 * @return possible object is {@link Localization }
	 * 
	 */
	public Localization getLocalization()
	{
		return localization;
	}

	/**
	 * Sets the value of the localization property.
	 * 
	 * @param value
	 *           allowed object is {@link Localization }
	 * 
	 */
	public void setLocalization(final Localization value)
	{
		this.localization = value;
	}

}
