//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Used in authentication of the sender's identity.
 * 
 * <p>
 * Java class for WebAuthenticationDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebAuthenticationDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserCredential" type="{http://fedex.com/ws/track/v8}WebAuthenticationCredential"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebAuthenticationDetail", propOrder =
{ "userCredential" })
@XmlRootElement(name = "WebAuthenticationDetail")
public class WebAuthenticationDetail
{

	@XmlElement(name = "UserCredential", required = true)
	protected WebAuthenticationCredential userCredential;

	/**
	 * Gets the value of the userCredential property.
	 * 
	 * @return possible object is {@link WebAuthenticationCredential }
	 * 
	 */
	public WebAuthenticationCredential getUserCredential()
	{
		return userCredential;
	}

	/**
	 * Sets the value of the userCredential property.
	 * 
	 * @param value
	 *           allowed object is {@link WebAuthenticationCredential }
	 * 
	 */
	public void setUserCredential(final WebAuthenticationCredential value)
	{
		this.userCredential = value;
	}

}
