//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 03:15:50 PM IST 
//


package com.jnj.itsusmpl00082.sg910_btb_in0498_salesorder_global_source_v1_webservice.salesorderws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for salesOrderPricingWrapper complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesOrderPricingWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="salesOrderPricingRequest" type="{http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS}salesOrderPricingRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesOrderPricingWrapper", propOrder =
{ "salesOrderPricingRequest" })
@XmlRootElement(name = "SalesOrderPricingWrapper")
public class SalesOrderPricingWrapper
{

	@XmlElement(required = true, nillable = true)
	protected SalesOrderPricingRequest salesOrderPricingRequest;

	/**
	 * Gets the value of the salesOrderPricingRequest property.
	 * 
	 * @return possible object is {@link SalesOrderPricingRequest }
	 * 
	 */
	public SalesOrderPricingRequest getSalesOrderPricingRequest()
	{
		return salesOrderPricingRequest;
	}

	/**
	 * Sets the value of the salesOrderPricingRequest property.
	 * 
	 * @param value
	 *           allowed object is {@link SalesOrderPricingRequest }
	 * 
	 */
	public void setSalesOrderPricingRequest(final SalesOrderPricingRequest value)
	{
		this.salesOrderPricingRequest = value;
	}

}
