//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:21:19 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_contractprice_v1.getcontractpricewrapperwebservice;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for ContractPriceReply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractPriceReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Division" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldToCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipToCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Material" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderLineQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HigherLevelItemNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comp8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Per" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentTerms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceContractNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GovernmentContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PeriodNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TierNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceTierNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExclusiveIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreightCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HandlingCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommissionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceListNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceListDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractValueIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GPOName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EChannelIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransactionStartTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OpCoResponseTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InterfaceCallResponseTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransactionResponseTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correlationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interfaceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceProgramID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="responseDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="components" type="{http://hcswmd01.jnj.com/MU007_EPIC_ContractPrice_v1/getContractPriceWrapperWebservice}component" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractPriceReply", propOrder =
{ "division", "orderType", "soldToCustomer", "shipToCustomer", "material", "orderLineQuantity", "higherLevelItemNumber",
		"contractPrice", "comp1", "comp2", "comp3", "comp4", "comp5", "comp6", "comp7", "comp8", "uom", "per", "currency",
		"priceDate", "orderChannel", "orderSource", "paymentTerms", "contractNumber", "referenceContractNumber",
		"governmentContractNumber", "periodNumber", "tierNumber", "referenceTierNumber", "exclusiveIndicator", "freightCode",
		"handlingCode", "commissionCode", "priceGroup", "contractGroup", "contractGroupDescription", "priceListNumber",
		"priceListDescription", "contractStartDate", "contractEndDate", "contractValueIndicator", "gpoName", "contractName",
		"eChannelIndicator", "transactionStartTime", "opCoResponseTime", "interfaceCallResponseTime", "transactionResponseTime",
		"correlationID", "interfaceID", "system", "username", "priceProgramID", "responseDateTime", "components" })
@XmlRootElement(name = "ContractPriceReply")
public class ContractPriceReply
{

	@XmlElement(name = "Division", required = true, nillable = true)
	protected String division;
	@XmlElementRef(name = "OrderType", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderType;
	@XmlElementRef(name = "SoldToCustomer", type = JAXBElement.class, required = false)
	protected JAXBElement<String> soldToCustomer;
	@XmlElementRef(name = "ShipToCustomer", type = JAXBElement.class, required = false)
	protected JAXBElement<String> shipToCustomer;
	@XmlElement(name = "Material", required = true, nillable = true)
	protected String material;
	@XmlElementRef(name = "OrderLineQuantity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderLineQuantity;
	@XmlElementRef(name = "HigherLevelItemNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> higherLevelItemNumber;
	@XmlElementRef(name = "ContractPrice", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractPrice;
	@XmlElementRef(name = "Comp1", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp1;
	@XmlElementRef(name = "Comp2", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp2;
	@XmlElementRef(name = "Comp3", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp3;
	@XmlElementRef(name = "Comp4", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp4;
	@XmlElementRef(name = "Comp5", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp5;
	@XmlElementRef(name = "Comp6", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp6;
	@XmlElementRef(name = "Comp7", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp7;
	@XmlElementRef(name = "Comp8", type = JAXBElement.class, required = false)
	protected JAXBElement<String> comp8;
	@XmlElementRef(name = "UOM", type = JAXBElement.class, required = false)
	protected JAXBElement<String> uom;
	@XmlElementRef(name = "Per", type = JAXBElement.class, required = false)
	protected JAXBElement<String> per;
	@XmlElementRef(name = "Currency", type = JAXBElement.class, required = false)
	protected JAXBElement<String> currency;
	@XmlElementRef(name = "PriceDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceDate;
	@XmlElementRef(name = "OrderChannel", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderChannel;
	@XmlElementRef(name = "OrderSource", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderSource;
	@XmlElementRef(name = "PaymentTerms", type = JAXBElement.class, required = false)
	protected JAXBElement<String> paymentTerms;
	@XmlElementRef(name = "ContractNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractNumber;
	@XmlElement(name = "ReferenceContractNumber", required = true, nillable = true)
	protected String referenceContractNumber;
	@XmlElementRef(name = "GovernmentContractNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> governmentContractNumber;
	@XmlElementRef(name = "PeriodNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> periodNumber;
	@XmlElementRef(name = "TierNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> tierNumber;
	@XmlElement(name = "ReferenceTierNumber", required = true, nillable = true)
	protected String referenceTierNumber;
	@XmlElementRef(name = "ExclusiveIndicator", type = JAXBElement.class, required = false)
	protected JAXBElement<String> exclusiveIndicator;
	@XmlElementRef(name = "FreightCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> freightCode;
	@XmlElementRef(name = "HandlingCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> handlingCode;
	@XmlElementRef(name = "CommissionCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> commissionCode;
	@XmlElementRef(name = "PriceGroup", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceGroup;
	@XmlElementRef(name = "ContractGroup", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractGroup;
	@XmlElementRef(name = "ContractGroupDescription", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractGroupDescription;
	@XmlElementRef(name = "PriceListNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceListNumber;
	@XmlElementRef(name = "PriceListDescription", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceListDescription;
	@XmlElementRef(name = "ContractStartDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractStartDate;
	@XmlElementRef(name = "ContractEndDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractEndDate;
	@XmlElementRef(name = "ContractValueIndicator", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractValueIndicator;
	@XmlElementRef(name = "GPOName", type = JAXBElement.class, required = false)
	protected JAXBElement<String> gpoName;
	@XmlElementRef(name = "ContractName", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractName;
	@XmlElementRef(name = "EChannelIndicator", type = JAXBElement.class, required = false)
	protected JAXBElement<String> eChannelIndicator;
	@XmlElementRef(name = "TransactionStartTime", type = JAXBElement.class, required = false)
	protected JAXBElement<String> transactionStartTime;
	@XmlElementRef(name = "OpCoResponseTime", type = JAXBElement.class, required = false)
	protected JAXBElement<String> opCoResponseTime;
	@XmlElementRef(name = "InterfaceCallResponseTime", type = JAXBElement.class, required = false)
	protected JAXBElement<String> interfaceCallResponseTime;
	@XmlElementRef(name = "TransactionResponseTime", type = JAXBElement.class, required = false)
	protected JAXBElement<String> transactionResponseTime;
	@XmlElementRef(name = "correlationID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> correlationID;
	@XmlElementRef(name = "interfaceID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> interfaceID;
	@XmlElementRef(name = "System", type = JAXBElement.class, required = false)
	protected JAXBElement<String> system;
	@XmlElementRef(name = "Username", type = JAXBElement.class, required = false)
	protected JAXBElement<String> username;
	@XmlElementRef(name = "PriceProgramID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceProgramID;
	@XmlElementRef(name = "responseDateTime", type = JAXBElement.class, required = false)
	protected JAXBElement<String> responseDateTime;
	@XmlElement(nillable = true)
	protected List<Component> components;

	/**
	 * Gets the value of the division property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDivision()
	{
		return division;
	}

	/**
	 * Sets the value of the division property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setDivision(final String value)
	{
		this.division = value;
	}

	/**
	 * Gets the value of the orderType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderType()
	{
		return orderType;
	}

	/**
	 * Sets the value of the orderType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderType(final JAXBElement<String> value)
	{
		this.orderType = value;
	}

	/**
	 * Gets the value of the soldToCustomer property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSoldToCustomer()
	{
		return soldToCustomer;
	}

	/**
	 * Sets the value of the soldToCustomer property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSoldToCustomer(final JAXBElement<String> value)
	{
		this.soldToCustomer = value;
	}

	/**
	 * Gets the value of the shipToCustomer property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getShipToCustomer()
	{
		return shipToCustomer;
	}

	/**
	 * Sets the value of the shipToCustomer property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setShipToCustomer(final JAXBElement<String> value)
	{
		this.shipToCustomer = value;
	}

	/**
	 * Gets the value of the material property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaterial()
	{
		return material;
	}

	/**
	 * Sets the value of the material property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMaterial(final String value)
	{
		this.material = value;
	}

	/**
	 * Gets the value of the orderLineQuantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderLineQuantity()
	{
		return orderLineQuantity;
	}

	/**
	 * Sets the value of the orderLineQuantity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderLineQuantity(final JAXBElement<String> value)
	{
		this.orderLineQuantity = value;
	}

	/**
	 * Gets the value of the higherLevelItemNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getHigherLevelItemNumber()
	{
		return higherLevelItemNumber;
	}

	/**
	 * Sets the value of the higherLevelItemNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setHigherLevelItemNumber(final JAXBElement<String> value)
	{
		this.higherLevelItemNumber = value;
	}

	/**
	 * Gets the value of the contractPrice property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractPrice()
	{
		return contractPrice;
	}

	/**
	 * Sets the value of the contractPrice property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractPrice(final JAXBElement<String> value)
	{
		this.contractPrice = value;
	}

	/**
	 * Gets the value of the comp1 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp1()
	{
		return comp1;
	}

	/**
	 * Sets the value of the comp1 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp1(final JAXBElement<String> value)
	{
		this.comp1 = value;
	}

	/**
	 * Gets the value of the comp2 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp2()
	{
		return comp2;
	}

	/**
	 * Sets the value of the comp2 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp2(final JAXBElement<String> value)
	{
		this.comp2 = value;
	}

	/**
	 * Gets the value of the comp3 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp3()
	{
		return comp3;
	}

	/**
	 * Sets the value of the comp3 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp3(final JAXBElement<String> value)
	{
		this.comp3 = value;
	}

	/**
	 * Gets the value of the comp4 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp4()
	{
		return comp4;
	}

	/**
	 * Sets the value of the comp4 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp4(final JAXBElement<String> value)
	{
		this.comp4 = value;
	}

	/**
	 * Gets the value of the comp5 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp5()
	{
		return comp5;
	}

	/**
	 * Sets the value of the comp5 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp5(final JAXBElement<String> value)
	{
		this.comp5 = value;
	}

	/**
	 * Gets the value of the comp6 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp6()
	{
		return comp6;
	}

	/**
	 * Sets the value of the comp6 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp6(final JAXBElement<String> value)
	{
		this.comp6 = value;
	}

	/**
	 * Gets the value of the comp7 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp7()
	{
		return comp7;
	}

	/**
	 * Sets the value of the comp7 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp7(final JAXBElement<String> value)
	{
		this.comp7 = value;
	}

	/**
	 * Gets the value of the comp8 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getComp8()
	{
		return comp8;
	}

	/**
	 * Sets the value of the comp8 property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setComp8(final JAXBElement<String> value)
	{
		this.comp8 = value;
	}

	/**
	 * Gets the value of the uom property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUOM()
	{
		return uom;
	}

	/**
	 * Sets the value of the uom property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUOM(final JAXBElement<String> value)
	{
		this.uom = value;
	}

	/**
	 * Gets the value of the per property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPer()
	{
		return per;
	}

	/**
	 * Sets the value of the per property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPer(final JAXBElement<String> value)
	{
		this.per = value;
	}

	/**
	 * Gets the value of the currency property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCurrency()
	{
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCurrency(final JAXBElement<String> value)
	{
		this.currency = value;
	}

	/**
	 * Gets the value of the priceDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceDate()
	{
		return priceDate;
	}

	/**
	 * Sets the value of the priceDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceDate(final JAXBElement<String> value)
	{
		this.priceDate = value;
	}

	/**
	 * Gets the value of the orderChannel property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderChannel()
	{
		return orderChannel;
	}

	/**
	 * Sets the value of the orderChannel property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderChannel(final JAXBElement<String> value)
	{
		this.orderChannel = value;
	}

	/**
	 * Gets the value of the orderSource property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderSource()
	{
		return orderSource;
	}

	/**
	 * Sets the value of the orderSource property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderSource(final JAXBElement<String> value)
	{
		this.orderSource = value;
	}

	/**
	 * Gets the value of the paymentTerms property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPaymentTerms()
	{
		return paymentTerms;
	}

	/**
	 * Sets the value of the paymentTerms property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPaymentTerms(final JAXBElement<String> value)
	{
		this.paymentTerms = value;
	}

	/**
	 * Gets the value of the contractNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractNumber()
	{
		return contractNumber;
	}

	/**
	 * Sets the value of the contractNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractNumber(final JAXBElement<String> value)
	{
		this.contractNumber = value;
	}

	/**
	 * Gets the value of the referenceContractNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceContractNumber()
	{
		return referenceContractNumber;
	}

	/**
	 * Sets the value of the referenceContractNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setReferenceContractNumber(final String value)
	{
		this.referenceContractNumber = value;
	}

	/**
	 * Gets the value of the governmentContractNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getGovernmentContractNumber()
	{
		return governmentContractNumber;
	}

	/**
	 * Sets the value of the governmentContractNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setGovernmentContractNumber(final JAXBElement<String> value)
	{
		this.governmentContractNumber = value;
	}

	/**
	 * Gets the value of the periodNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPeriodNumber()
	{
		return periodNumber;
	}

	/**
	 * Sets the value of the periodNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPeriodNumber(final JAXBElement<String> value)
	{
		this.periodNumber = value;
	}

	/**
	 * Gets the value of the tierNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getTierNumber()
	{
		return tierNumber;
	}

	/**
	 * Sets the value of the tierNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setTierNumber(final JAXBElement<String> value)
	{
		this.tierNumber = value;
	}

	/**
	 * Gets the value of the referenceTierNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceTierNumber()
	{
		return referenceTierNumber;
	}

	/**
	 * Sets the value of the referenceTierNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setReferenceTierNumber(final String value)
	{
		this.referenceTierNumber = value;
	}

	/**
	 * Gets the value of the exclusiveIndicator property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getExclusiveIndicator()
	{
		return exclusiveIndicator;
	}

	/**
	 * Sets the value of the exclusiveIndicator property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setExclusiveIndicator(final JAXBElement<String> value)
	{
		this.exclusiveIndicator = value;
	}

	/**
	 * Gets the value of the freightCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getFreightCode()
	{
		return freightCode;
	}

	/**
	 * Sets the value of the freightCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setFreightCode(final JAXBElement<String> value)
	{
		this.freightCode = value;
	}

	/**
	 * Gets the value of the handlingCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getHandlingCode()
	{
		return handlingCode;
	}

	/**
	 * Sets the value of the handlingCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setHandlingCode(final JAXBElement<String> value)
	{
		this.handlingCode = value;
	}

	/**
	 * Gets the value of the commissionCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCommissionCode()
	{
		return commissionCode;
	}

	/**
	 * Sets the value of the commissionCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCommissionCode(final JAXBElement<String> value)
	{
		this.commissionCode = value;
	}

	/**
	 * Gets the value of the priceGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceGroup()
	{
		return priceGroup;
	}

	/**
	 * Sets the value of the priceGroup property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceGroup(final JAXBElement<String> value)
	{
		this.priceGroup = value;
	}

	/**
	 * Gets the value of the contractGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractGroup()
	{
		return contractGroup;
	}

	/**
	 * Sets the value of the contractGroup property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractGroup(final JAXBElement<String> value)
	{
		this.contractGroup = value;
	}

	/**
	 * Gets the value of the contractGroupDescription property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractGroupDescription()
	{
		return contractGroupDescription;
	}

	/**
	 * Sets the value of the contractGroupDescription property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractGroupDescription(final JAXBElement<String> value)
	{
		this.contractGroupDescription = value;
	}

	/**
	 * Gets the value of the priceListNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceListNumber()
	{
		return priceListNumber;
	}

	/**
	 * Sets the value of the priceListNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceListNumber(final JAXBElement<String> value)
	{
		this.priceListNumber = value;
	}

	/**
	 * Gets the value of the priceListDescription property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceListDescription()
	{
		return priceListDescription;
	}

	/**
	 * Sets the value of the priceListDescription property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceListDescription(final JAXBElement<String> value)
	{
		this.priceListDescription = value;
	}

	/**
	 * Gets the value of the contractStartDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractStartDate()
	{
		return contractStartDate;
	}

	/**
	 * Sets the value of the contractStartDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractStartDate(final JAXBElement<String> value)
	{
		this.contractStartDate = value;
	}

	/**
	 * Gets the value of the contractEndDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractEndDate()
	{
		return contractEndDate;
	}

	/**
	 * Sets the value of the contractEndDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractEndDate(final JAXBElement<String> value)
	{
		this.contractEndDate = value;
	}

	/**
	 * Gets the value of the contractValueIndicator property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractValueIndicator()
	{
		return contractValueIndicator;
	}

	/**
	 * Sets the value of the contractValueIndicator property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractValueIndicator(final JAXBElement<String> value)
	{
		this.contractValueIndicator = value;
	}

	/**
	 * Gets the value of the gpoName property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getGPOName()
	{
		return gpoName;
	}

	/**
	 * Sets the value of the gpoName property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setGPOName(final JAXBElement<String> value)
	{
		this.gpoName = value;
	}

	/**
	 * Gets the value of the contractName property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractName()
	{
		return contractName;
	}

	/**
	 * Sets the value of the contractName property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractName(final JAXBElement<String> value)
	{
		this.contractName = value;
	}

	/**
	 * Gets the value of the eChannelIndicator property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getEChannelIndicator()
	{
		return eChannelIndicator;
	}

	/**
	 * Sets the value of the eChannelIndicator property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setEChannelIndicator(final JAXBElement<String> value)
	{
		this.eChannelIndicator = value;
	}

	/**
	 * Gets the value of the transactionStartTime property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getTransactionStartTime()
	{
		return transactionStartTime;
	}

	/**
	 * Sets the value of the transactionStartTime property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setTransactionStartTime(final JAXBElement<String> value)
	{
		this.transactionStartTime = value;
	}

	/**
	 * Gets the value of the opCoResponseTime property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOpCoResponseTime()
	{
		return opCoResponseTime;
	}

	/**
	 * Sets the value of the opCoResponseTime property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOpCoResponseTime(final JAXBElement<String> value)
	{
		this.opCoResponseTime = value;
	}

	/**
	 * Gets the value of the interfaceCallResponseTime property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInterfaceCallResponseTime()
	{
		return interfaceCallResponseTime;
	}

	/**
	 * Sets the value of the interfaceCallResponseTime property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInterfaceCallResponseTime(final JAXBElement<String> value)
	{
		this.interfaceCallResponseTime = value;
	}

	/**
	 * Gets the value of the transactionResponseTime property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getTransactionResponseTime()
	{
		return transactionResponseTime;
	}

	/**
	 * Sets the value of the transactionResponseTime property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setTransactionResponseTime(final JAXBElement<String> value)
	{
		this.transactionResponseTime = value;
	}

	/**
	 * Gets the value of the correlationID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCorrelationID()
	{
		return correlationID;
	}

	/**
	 * Sets the value of the correlationID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCorrelationID(final JAXBElement<String> value)
	{
		this.correlationID = value;
	}

	/**
	 * Gets the value of the interfaceID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInterfaceID()
	{
		return interfaceID;
	}

	/**
	 * Sets the value of the interfaceID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInterfaceID(final JAXBElement<String> value)
	{
		this.interfaceID = value;
	}

	/**
	 * Gets the value of the system property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSystem()
	{
		return system;
	}

	/**
	 * Sets the value of the system property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSystem(final JAXBElement<String> value)
	{
		this.system = value;
	}

	/**
	 * Gets the value of the username property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUsername()
	{
		return username;
	}

	/**
	 * Sets the value of the username property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUsername(final JAXBElement<String> value)
	{
		this.username = value;
	}

	/**
	 * Gets the value of the priceProgramID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceProgramID()
	{
		return priceProgramID;
	}

	/**
	 * Sets the value of the priceProgramID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceProgramID(final JAXBElement<String> value)
	{
		this.priceProgramID = value;
	}

	/**
	 * Gets the value of the responseDateTime property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getResponseDateTime()
	{
		return responseDateTime;
	}

	/**
	 * Sets the value of the responseDateTime property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setResponseDateTime(final JAXBElement<String> value)
	{
		this.responseDateTime = value;
	}

	/**
	 * Gets the value of the components property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the components property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getComponents().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Component }
	 * 
	 * 
	 */
	public List<Component> getComponents()
	{
		if (components == null)
		{
			components = new ArrayList<Component>();
		}
		return this.components;
	}

}
