//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:21:19 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_contractprice_v1.getcontractpricewrapperwebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for ContractPriceRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractPriceRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SYNC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Division" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SoldToCustomer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipToCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Material" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HigherLevelItem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PricingDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommissionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TierNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correlationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interfaceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EChannelIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startTransactionTiming" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="System" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractPriceRequest", propOrder =
{ "sync", "division", "orderType", "soldToCustomer", "shipToCustomer", "material", "higherLevelItem", "uom", "pricingDate",
		"orderQuantity", "commissionCode", "orderChannel", "orderSource", "currency", "contractNumber", "tierNumber",
		"correlationID", "interfaceID", "eChannelIndicator", "startTransactionTiming", "username", "system" })
@XmlRootElement(name = "ContractPriceRequest")
public class ContractPriceRequest
{

	@XmlElementRef(name = "SYNC", type = JAXBElement.class, required = false)
	protected JAXBElement<String> sync;
	@XmlElement(name = "Division", required = true, nillable = true)
	protected String division;
	@XmlElementRef(name = "OrderType", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderType;
	@XmlElement(name = "SoldToCustomer", required = true, nillable = true)
	protected String soldToCustomer;
	@XmlElementRef(name = "ShipToCustomer", type = JAXBElement.class, required = false)
	protected JAXBElement<String> shipToCustomer;
	@XmlElement(name = "Material", required = true, nillable = true)
	protected String material;
	@XmlElementRef(name = "HigherLevelItem", type = JAXBElement.class, required = false)
	protected JAXBElement<String> higherLevelItem;
	@XmlElementRef(name = "UOM", type = JAXBElement.class, required = false)
	protected JAXBElement<String> uom;
	@XmlElementRef(name = "PricingDate", type = JAXBElement.class, required = false)
	protected JAXBElement<String> pricingDate;
	@XmlElementRef(name = "OrderQuantity", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderQuantity;
	@XmlElementRef(name = "CommissionCode", type = JAXBElement.class, required = false)
	protected JAXBElement<String> commissionCode;
	@XmlElementRef(name = "OrderChannel", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderChannel;
	@XmlElementRef(name = "OrderSource", type = JAXBElement.class, required = false)
	protected JAXBElement<String> orderSource;
	@XmlElementRef(name = "Currency", type = JAXBElement.class, required = false)
	protected JAXBElement<String> currency;
	@XmlElementRef(name = "ContractNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> contractNumber;
	@XmlElementRef(name = "TierNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> tierNumber;
	@XmlElementRef(name = "correlationID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> correlationID;
	@XmlElementRef(name = "interfaceID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> interfaceID;
	@XmlElementRef(name = "EChannelIndicator", type = JAXBElement.class, required = false)
	protected JAXBElement<String> eChannelIndicator;
	@XmlElement(required = true, nillable = true)
	protected String startTransactionTiming;
	@XmlElementRef(name = "Username", type = JAXBElement.class, required = false)
	protected JAXBElement<String> username;
	@XmlElementRef(name = "System", type = JAXBElement.class, required = false)
	protected JAXBElement<String> system;

	/**
	 * Gets the value of the sync property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSYNC()
	{
		return sync;
	}

	/**
	 * Sets the value of the sync property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSYNC(final JAXBElement<String> value)
	{
		this.sync = value;
	}

	/**
	 * Gets the value of the division property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDivision()
	{
		return division;
	}

	/**
	 * Sets the value of the division property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setDivision(final String value)
	{
		this.division = value;
	}

	/**
	 * Gets the value of the orderType property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderType()
	{
		return orderType;
	}

	/**
	 * Sets the value of the orderType property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderType(final JAXBElement<String> value)
	{
		this.orderType = value;
	}

	/**
	 * Gets the value of the soldToCustomer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoldToCustomer()
	{
		return soldToCustomer;
	}

	/**
	 * Sets the value of the soldToCustomer property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setSoldToCustomer(final String value)
	{
		this.soldToCustomer = value;
	}

	/**
	 * Gets the value of the shipToCustomer property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getShipToCustomer()
	{
		return shipToCustomer;
	}

	/**
	 * Sets the value of the shipToCustomer property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setShipToCustomer(final JAXBElement<String> value)
	{
		this.shipToCustomer = value;
	}

	/**
	 * Gets the value of the material property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaterial()
	{
		return material;
	}

	/**
	 * Sets the value of the material property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMaterial(final String value)
	{
		this.material = value;
	}

	/**
	 * Gets the value of the higherLevelItem property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getHigherLevelItem()
	{
		return higherLevelItem;
	}

	/**
	 * Sets the value of the higherLevelItem property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setHigherLevelItem(final JAXBElement<String> value)
	{
		this.higherLevelItem = value;
	}

	/**
	 * Gets the value of the uom property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUOM()
	{
		return uom;
	}

	/**
	 * Sets the value of the uom property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUOM(final JAXBElement<String> value)
	{
		this.uom = value;
	}

	/**
	 * Gets the value of the pricingDate property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPricingDate()
	{
		return pricingDate;
	}

	/**
	 * Sets the value of the pricingDate property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPricingDate(final JAXBElement<String> value)
	{
		this.pricingDate = value;
	}

	/**
	 * Gets the value of the orderQuantity property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderQuantity()
	{
		return orderQuantity;
	}

	/**
	 * Sets the value of the orderQuantity property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderQuantity(final JAXBElement<String> value)
	{
		this.orderQuantity = value;
	}

	/**
	 * Gets the value of the commissionCode property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCommissionCode()
	{
		return commissionCode;
	}

	/**
	 * Sets the value of the commissionCode property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCommissionCode(final JAXBElement<String> value)
	{
		this.commissionCode = value;
	}

	/**
	 * Gets the value of the orderChannel property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderChannel()
	{
		return orderChannel;
	}

	/**
	 * Sets the value of the orderChannel property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderChannel(final JAXBElement<String> value)
	{
		this.orderChannel = value;
	}

	/**
	 * Gets the value of the orderSource property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getOrderSource()
	{
		return orderSource;
	}

	/**
	 * Sets the value of the orderSource property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setOrderSource(final JAXBElement<String> value)
	{
		this.orderSource = value;
	}

	/**
	 * Gets the value of the currency property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCurrency()
	{
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCurrency(final JAXBElement<String> value)
	{
		this.currency = value;
	}

	/**
	 * Gets the value of the contractNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getContractNumber()
	{
		return contractNumber;
	}

	/**
	 * Sets the value of the contractNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setContractNumber(final JAXBElement<String> value)
	{
		this.contractNumber = value;
	}

	/**
	 * Gets the value of the tierNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getTierNumber()
	{
		return tierNumber;
	}

	/**
	 * Sets the value of the tierNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setTierNumber(final JAXBElement<String> value)
	{
		this.tierNumber = value;
	}

	/**
	 * Gets the value of the correlationID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCorrelationID()
	{
		return correlationID;
	}

	/**
	 * Sets the value of the correlationID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCorrelationID(final JAXBElement<String> value)
	{
		this.correlationID = value;
	}

	/**
	 * Gets the value of the interfaceID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getInterfaceID()
	{
		return interfaceID;
	}

	/**
	 * Sets the value of the interfaceID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setInterfaceID(final JAXBElement<String> value)
	{
		this.interfaceID = value;
	}

	/**
	 * Gets the value of the eChannelIndicator property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getEChannelIndicator()
	{
		return eChannelIndicator;
	}

	/**
	 * Sets the value of the eChannelIndicator property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setEChannelIndicator(final JAXBElement<String> value)
	{
		this.eChannelIndicator = value;
	}

	/**
	 * Gets the value of the startTransactionTiming property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStartTransactionTiming()
	{
		return startTransactionTiming;
	}

	/**
	 * Sets the value of the startTransactionTiming property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setStartTransactionTiming(final String value)
	{
		this.startTransactionTiming = value;
	}

	/**
	 * Gets the value of the username property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUsername()
	{
		return username;
	}

	/**
	 * Sets the value of the username property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUsername(final JAXBElement<String> value)
	{
		this.username = value;
	}

	/**
	 * Gets the value of the system property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getSystem()
	{
		return system;
	}

	/**
	 * Sets the value of the system property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setSystem(final JAXBElement<String> value)
	{
		this.system = value;
	}

}
