//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:21:19 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_contractprice_v1.getcontractpricewrapperwebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for getContractPriceWrapperResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getContractPriceWrapperResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractPriceReply" type="{http://hcswmd01.jnj.com/MU007_EPIC_ContractPrice_v1/getContractPriceWrapperWebservice}ContractPriceReply"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getContractPriceWrapperResponse", propOrder =
{ "status", "errorMessage", "contractPriceReply" })
@XmlRootElement(name = "GetContractPriceWrapperResponse")
public class GetContractPriceWrapperResponse
{

	@XmlElement(name = "Status", required = true, nillable = true)
	protected String status;
	@XmlElementRef(name = "errorMessage", type = JAXBElement.class, required = false)
	protected JAXBElement<String> errorMessage;
	@XmlElement(name = "ContractPriceReply", required = true, nillable = true)
	protected ContractPriceReply contractPriceReply;

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setStatus(final String value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the errorMessage property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getErrorMessage()
	{
		return errorMessage;
	}

	/**
	 * Sets the value of the errorMessage property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setErrorMessage(final JAXBElement<String> value)
	{
		this.errorMessage = value;
	}

	/**
	 * Gets the value of the contractPriceReply property.
	 * 
	 * @return possible object is {@link ContractPriceReply }
	 * 
	 */
	public ContractPriceReply getContractPriceReply()
	{
		return contractPriceReply;
	}

	/**
	 * Sets the value of the contractPriceReply property.
	 * 
	 * @param value
	 *           allowed object is {@link ContractPriceReply }
	 * 
	 */
	public void setContractPriceReply(final ContractPriceReply value)
	{
		this.contractPriceReply = value;
	}

}
