//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:02:08 PM IST 
//


package com.jnj.hcswmd01.mu007_epic_reports_cmod_v1.wsd.getreports;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for Filter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reports" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Topics" type="{http://hcswmd01.jnj.com/MU007_EPIC_Reports_CMOD_v1/wsd/getReports}Topics" maxOccurs="unbounded"/>
 *         &lt;element name="Formats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filter", propOrder =
{ "reports", "topics", "formats", "dateFrom", "dateTo" })
@XmlRootElement(name = "Filter")
public class Filter
{

	@XmlElement(name = "Reports", required = true, nillable = true)
	protected String reports;
	@XmlElement(name = "Topics", required = true, nillable = true)
	protected List<Topics> topics;
	@XmlElementRef(name = "Formats", type = JAXBElement.class, required = false)
	protected JAXBElement<String> formats;
	@XmlElementRef(name = "DateFrom", type = JAXBElement.class, required = false)
	protected JAXBElement<String> dateFrom;
	@XmlElement(name = "DateTo", required = true, nillable = true)
	protected String dateTo;

	/**
	 * Gets the value of the reports property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReports()
	{
		return reports;
	}

	/**
	 * Sets the value of the reports property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setReports(final String value)
	{
		this.reports = value;
	}

	/**
	 * Gets the value of the topics property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the topics property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTopics().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Topics }
	 * 
	 * 
	 */
	public List<Topics> getTopics()
	{
		if (topics == null)
		{
			topics = new ArrayList<Topics>();
		}
		return this.topics;
	}

	/**
	 * Gets the value of the formats property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getFormats()
	{
		return formats;
	}

	/**
	 * Sets the value of the formats property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setFormats(final JAXBElement<String> value)
	{
		this.formats = value;
	}

	/**
	 * Gets the value of the dateFrom property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getDateFrom()
	{
		return dateFrom;
	}

	/**
	 * Sets the value of the dateFrom property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setDateFrom(final JAXBElement<String> value)
	{
		this.dateFrom = value;
	}

	/**
	 * Gets the value of the dateTo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDateTo()
	{
		return dateTo;
	}

	/**
	 * Sets the value of the dateTo property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setDateTo(final String value)
	{
		this.dateTo = value;
	}

}
