//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:02:08 PM IST 
//


package com.jnj.hcswmd01.mu007_epic_reports_cmod_v1.wsd.getreports;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for ReportsReply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportsReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportReply" type="{http://hcswmd01.jnj.com/MU007_EPIC_Reports_CMOD_v1/wsd/getReports}ReportReply" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportsReply", propOrder =
{ "reportReply" })
@XmlRootElement(name = "ReportsReply")
public class ReportsReply
{

	@XmlElementRef(name = "ReportReply", type = JAXBElement.class, required = false)
	protected JAXBElement<ReportReply> reportReply;

	/**
	 * Gets the value of the reportReply property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link ReportReply }{@code >}
	 * 
	 */
	public JAXBElement<ReportReply> getReportReply()
	{
		return reportReply;
	}

	/**
	 * Sets the value of the reportReply property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link ReportReply }{@code >}
	 * 
	 */
	public void setReportReply(final JAXBElement<ReportReply> value)
	{
		this.reportReply = value;
	}

}
