//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:02:08 PM IST 
//


package com.jnj.hcswmd01.mu007_epic_reports_cmod_v1.wsd.getreports;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for ReportReply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportReply">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CorrelationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PDFReferenceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PDFAttachment" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportReply", propOrder =
{ "correlationID", "pdfReferenceName", "pdfAttachment", "status", "errorMessage" })
@XmlRootElement(name = "ReportReply")
public class ReportReply
{

	@XmlElementRef(name = "CorrelationID", type = JAXBElement.class, required = false)
	protected JAXBElement<String> correlationID;
	@XmlElementRef(name = "PDFReferenceName", type = JAXBElement.class, required = false)
	protected JAXBElement<String> pdfReferenceName;
	@XmlElementRef(name = "PDFAttachment", type = JAXBElement.class, required = false)
	protected JAXBElement<byte[]> pdfAttachment;
	@XmlElementRef(name = "status", type = JAXBElement.class, required = false)
	protected JAXBElement<String> status;
	@XmlElementRef(name = "errorMessage", type = JAXBElement.class, required = false)
	protected JAXBElement<String> errorMessage;

	/**
	 * Gets the value of the correlationID property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCorrelationID()
	{
		return correlationID;
	}

	/**
	 * Sets the value of the correlationID property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCorrelationID(final JAXBElement<String> value)
	{
		this.correlationID = value;
	}

	/**
	 * Gets the value of the pdfReferenceName property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPDFReferenceName()
	{
		return pdfReferenceName;
	}

	/**
	 * Sets the value of the pdfReferenceName property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPDFReferenceName(final JAXBElement<String> value)
	{
		this.pdfReferenceName = value;
	}

	/**
	 * Gets the value of the pdfAttachment property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	public JAXBElement<byte[]> getPDFAttachment()
	{
		return pdfAttachment;
	}

	/**
	 * Sets the value of the pdfAttachment property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	public void setPDFAttachment(final JAXBElement<byte[]> value)
	{
		this.pdfAttachment = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setStatus(final JAXBElement<String> value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the errorMessage property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getErrorMessage()
	{
		return errorMessage;
	}

	/**
	 * Sets the value of the errorMessage property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setErrorMessage(final JAXBElement<String> value)
	{
		this.errorMessage = value;
	}

}
