/*
 * This code contains copyright information which is the proprietary property
 * of JNJ Companies Ltd. No part of this code may be reproduced, stored or
 * transmitted in any form without the prior written permission of JNJ Companies Ltd.
 * Copyright (C) JNJ Companies Ltd 2013
 * All rights reserved.
 */

package com.jnj.la.core.util;

import com.jcraft.jsch.Channel;
import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import com.jcraft.jsch.SftpException;
import com.jnj.core.constants.Jnjb2bCoreConstants;
import com.jnj.core.dto.FileUploadDTO;
import com.jnj.core.util.JnJCommonUtil;
import com.jnj.core.util.JnjFileUploadToSharedFolderUtil;
import com.jnj.core.util.JnjGTCoreUtil;
import com.jnj.core.util.JnjSftpFileTransferUtil;
import com.jnj.facades.constants.Jnjb2bFacadesConstants.Logging;
import com.jnj.la.core.constants.Jnjlab2bcoreConstants;
import com.jnj.la.core.dto.product.JnjRSAProductDTO;

import de.hybris.platform.util.Config;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.Properties;

import org.apache.log4j.Logger;
import org.apache.commons.lang3.StringUtils;


public class JnjLaSftpFileTransferUtil extends JnjSftpFileTransferUtil
{

	private static final Class currentClass = JnjLaSftpFileTransferUtil.class;

	private static final String EMPENHO_DOCS_TRANSFER = "Empenho Docs Transfer";
	private static final Logger LOG = Logger.getLogger(JnjLaSftpFileTransferUtil.class);
	
	private final String hostnameSubmitEdI = Config.getParameter(Jnjb2bCoreConstants.DocumenTransfer.SFTP_HOSTNAME_SUBMIT_EdI);

	private final String usernameSubmitEdI = Config.getParameter(Jnjb2bCoreConstants.DocumenTransfer.SFTP_USERNAME_SUBMIT_EdI);

	private final String passwordSubmitEdI = Config.getParameter(Jnjb2bCoreConstants.DocumenTransfer.SFTP_PASSWORD_SUBMIT_EdI);

	private final int portSubmitEdI = Integer.parseInt((Config
			.getParameter(Jnjb2bCoreConstants.DocumenTransfer.SFTP_PORT_SUBMIT_EdI)));

	/**
	 * Upload empenho docs to sftp, Files will be renamed to given SAP order number. In case of error in SFTP channel
	 * files will be moved to defined Error Folder.
	 *
	 * @param filePaths
	 *           the list of file path that need to be uploaded to SFTP Location
	 * @param sapOrderNumber
	 *           String required file name for SFTP location
	 * @param hybrisOrderNumber
	 *           String orderNumber generated by Hybris system
	 *
	 * @return true, if successful
	 */
	@Override
	public boolean uploadEmpenhoDocsToSftp(final List<String> filePaths, final String sapOrderNumber,
			final String hybrisOrderNumber)
	{
		final String methodName = "uploadEmpenhoDocsToSftp()";
		JnjGTCoreUtil.logDebugMessage(EMPENHO_DOCS_TRANSFER, methodName, Logging.BEGIN_OF_METHOD, currentClass);
		int count = 0;
		for (final String existingFilePath : filePaths)
		{
			final String existingFileName = existingFilePath.substring(existingFilePath.lastIndexOf(File.separator) + 1);
			final FileUploadDTO fileUploadDTO = new FileUploadDTO();
			//New names will be named with sap Order number + _1 _2 _3 ... so on
			final String newNameForEmpenhoDoc = JnjFileUploadToSharedFolderUtil.changeFileName(existingFileName,
					getNameForSMTP(++count, sapOrderNumber, hybrisOrderNumber));
			final String newPath = existingFilePath.replace(existingFileName, newNameForEmpenhoDoc);
			JnjFileUploadToSharedFolderUtil.renameFile(existingFilePath, newPath);

			fileUploadDTO.setFilePathInShareFolder(newPath);
			fileUploadDTO.setRemoteFilePath(Config.getParameter(Jnjb2bCoreConstants.UploadFile.SFTP_DESTINATION_EMPHENO_FOLDER));
			final boolean sftupUploadStatus = transferFileToSftp(fileUploadDTO);

			if (!sftupUploadStatus)
			{
				JnjGTCoreUtil.logDebugMessage(EMPENHO_DOCS_TRANSFER, methodName,
						"SFTP for file no " + count + " is not successful so moving it to error Folder", currentClass);
				final String errorInSeningFolderPath = Config
						.getParameter(Jnjb2bCoreConstants.UploadFile.FEED_FILEPATH_EMPENHO_DOC_ERROR).concat(File.separator)
						+ newNameForEmpenhoDoc;
				JnjFileUploadToSharedFolderUtil.renameFile(fileUploadDTO.getFilePathInShareFolder(), errorInSeningFolderPath);
			}
		}

		JnjGTCoreUtil.logDebugMessage(EMPENHO_DOCS_TRANSFER, methodName, Logging.END_OF_METHOD, currentClass);
		return true;
	}

	/**
	 * Tries to transfer a file to the SFPT folder up to 3 times
	 */
	private boolean transferFileToSftp(final FileUploadDTO fileUploadDTO)
	{
		final String methodName = "transferFileToSftp()";
		JnjGTCoreUtil.logInfoMessage(EMPENHO_DOCS_TRANSFER, methodName, Logging.BEGIN_OF_METHOD, currentClass);
		final boolean waitForRetry = Config.getBoolean(Jnjlab2bcoreConstants.Order.USE_RETRY_LOGIC_EMPENHO, false);
		final int connectionWaitPeriod = Config.getInt(Jnjlab2bcoreConstants.Order.EMPENHO_SFTP_CONNECTION_WAITING_TIME, 3);

		boolean result = false;
		final int maxAttempts = Config.getInt(Jnjlab2bcoreConstants.Order.EMPENHO_SFPT_TRANSFER_MAX_ATTEMPTS, 3);
		
		 // Tries to transfer the files up to maxAttempts times.
		try
		{
			for (int count = 1; count <= maxAttempts; count++) 
			{
				result = uploadFileToSftp(fileUploadDTO, Jnjb2bCoreConstants.UploadFile.SFTP_CONNECTION__TYPE_EMPHENO);
				JnjGTCoreUtil.logInfoMessage(
						EMPENHO_DOCS_TRANSFER, methodName, "Atempt # " + count + " to transfer the empenho file: "
								+ fileUploadDTO.getFilePathInShareFolder() + " to the SFPT folder. Transfer result: " + result,
						currentClass);
				
				if(count==maxAttempts && !result)
				{
					JnjGTCoreUtil.logInfoMessage(EMPENHO_DOCS_TRANSFER, methodName,
							"The empenho file transfer to SFTP got failed, Atempt###" + count + result+ " and the file name: "
									+ fileUploadDTO.getFilePathInShareFolder(),
							currentClass);
				}
				if (result)
				{
					break; // Files has been transferred successfully.
				}
				
				if(waitForRetry)
				{
					TimeUnit.SECONDS.sleep(connectionWaitPeriod); 
				}
			}
		}
		catch (InterruptedException exception)
		{
			LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + methodName + Logging.HYPHEN
					+ "Eexception occured while executing retry logic: " + exception.getMessage(), exception);
		}

		JnjGTCoreUtil.logInfoMessage(EMPENHO_DOCS_TRANSFER, methodName, Logging.END_OF_METHOD, currentClass);
		return result;
	}

	/**
	 * Gets the name for smtp name will have 5 diffrent components 1) Field 1: Fixed prefix IN0500 (length=6). 2) Field
	 * 2: SAP Order Number (length=10). 3) Field 3: Hybris Order Number (length=8). 4) Field 4: Sequential number
	 * (length=3). As the user is allowed to upload multiples files in a same order, this field can vary from 001 to 999
	 * allowing the user to upload up to 999 files per order. Two uploaded files must not have the same name. 5) Field 5:
	 * Date when the order was created on hybris in format MMDDYYYY (length=8). Example:
	 * IN0500_1234567890_12345678_123_12092013
	 *
	 * @param seqNum
	 *           the seq num
	 * @param sapOrderNum
	 *           the sap order num
	 * @param hybrisOrderNum
	 *           the hybris order num
	 * @return the name for smtp
	 */
	protected String getNameForSMTP(final int seqNum, final String sapOrderNum, final String hybrisOrderNum)
	{
		final StringBuffer name = new StringBuffer(JnJCommonUtil.getValue(Jnjb2bCoreConstants.EMPENHO_DOCS_PREFIX_KEY));
		name.append(Jnjb2bCoreConstants.UNDERSCORE_SYMBOL).append(sapOrderNum);
		name.append(Jnjb2bCoreConstants.UNDERSCORE_SYMBOL).append(hybrisOrderNum);
		name.append(Jnjb2bCoreConstants.UNDERSCORE_SYMBOL).append(String.format("%03d", seqNum));
		return name.toString();
	}
	
	//re try logic for EDI flow..
	
	public boolean uploadMultipleFileToSftp(final List<File> fileList, String remoteFilePath, final String sftpConnectionType)
	{
		if (LOG.isDebugEnabled())
		{
			LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
					+ Logging.BEGIN_OF_METHOD + Logging.HYPHEN + Logging.START_TIME + JnJCommonUtil.getCurrentDateTime());
		}
		Boolean sftpFlag = Boolean.FALSE;

		// check for the remoteFilePath if its not empty then enter in the if block.
		if (StringUtils.isNotEmpty(remoteFilePath))
		{
			// replace the backward slash with the forward slash.
			remoteFilePath = remoteFilePath.replace('\\', '/');
		}

		if (LOG.isDebugEnabled())
		{
			LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
					+ " SFTP: remoteFilePath " + remoteFilePath);
		}

		Session session = null;
		Channel channel = null;
		ChannelSftp channelSftp = null;
				
		final int retryAttempt = Config.getInt(Jnjlab2bcoreConstants.Order.SFTP_RETRY_ATTEMPTS, 3);
		final int connectionWaitPeriod = Config.getInt(Jnjlab2bcoreConstants.Order.SFTP_CONNECTION_WAITING_TIME, 60);
		try
		{

			for (int count = 0; count < retryAttempt; count++) 
			{
				Boolean reconnectSftp = Boolean.FALSE;
				if(count != 0)
				{
					TimeUnit.SECONDS.sleep(connectionWaitPeriod); 
				}				
		
				try
				{
					final JSch jsch = new JSch();
					if (Jnjb2bCoreConstants.UploadFile.SFTP_CONNECTION__TYPE_SUBMITEDI.equals(sftpConnectionType))
					{
						session = jsch.getSession(usernameSubmitEdI, hostnameSubmitEdI, portSubmitEdI);
						session.setPassword(passwordSubmitEdI);
						if (LOG.isDebugEnabled())
						{
							LOG.debug("SFTP: Connection Details  HostName:--> " + hostnameSubmitEdI + " UserName:-->" + usernameSubmitEdI
									+ " Port:-->" + portSubmitEdI + " Password Key:-->" + passwordSubmitEdI);
						}
					}

					final Properties config = new Properties();
					config.put("StrictHostKeyChecking", "no");
					session.setConfig(config);
					session.connect();
					channel = session.openChannel("sftp");
					channel.connect();
					if (LOG.isDebugEnabled())
					{
						LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
								+ " Connection Established" + remoteFilePath);
					}
					channelSftp = (ChannelSftp) channel;
					if (LOG.isDebugEnabled())
					{
						LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
								+ "Starting Change Directory " + remoteFilePath);
					}
					channelSftp.cd(remoteFilePath);
					if (LOG.isDebugEnabled())
					{
						LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
								+ " Directory Changed to Remote File Path" + remoteFilePath);
					}
					sftpFlag = true;
				}
				catch (final JSchException jschException)
				{
					LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
							+ "Jsch exception occured " + jschException.getMessage(), jschException);
					sftpFlag = false;
					reconnectSftp = true;
				}
				catch (final SftpException sftpException)
				{
					LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
							+ "SFTP exception occured " + sftpException.getMessage(), sftpException);
					sftpFlag = false;
					reconnectSftp = true;
				}
				
				LOG.info("ReconnectSftp value: "+reconnectSftp);
				
				if (!reconnectSftp) {
					break;
				}
			}
		}
		catch (Exception exception) 
		{
			LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "getSftpConnection()" + Logging.HYPHEN
					+ " SFTP: Error while reconnecting to SFTP server: " + exception);
		}
		
		// enters in the if block if the sftpFlag is true.
		if (sftpFlag)
		{
			for (final File file : fileList)
			{
				// check for the file is existed
				if (!file.exists())
				{
					LOG.error("SFTP: Error. Local file not found in the given location" + file);
					sftpFlag = false;
				}
				else
				{
					try(FileInputStream fileInputStream = new FileInputStream(file);)
					{
						if (LOG.isDebugEnabled())
						{
							LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
									+ Logging.HYPHEN + " File Input Stream " + fileInputStream);
						}
						channelSftp.put(fileInputStream, file.getName());
						if (LOG.isDebugEnabled())
						{
							LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
									+ Logging.HYPHEN + " After putting the content successfully in sftp folder");
						}
						channelSftp.ls(remoteFilePath);
						if (LOG.isDebugEnabled())
						{
							LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
									+ Logging.HYPHEN + " After getting the list of files from the sftp folder");
						}
						sftpFlag = true;
					}
					catch (final FileNotFoundException fileNotFoundException)
					{
						LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
								+ Logging.HYPHEN + "File Not Found exception occured " + fileNotFoundException.getMessage(),
								fileNotFoundException);
						sftpFlag = false;
					}
					catch (final SftpException sftpException)
					{
						LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
								+ Logging.HYPHEN + "SFTP exception occured " + sftpException.getMessage(), sftpException);
						sftpFlag = false;
					}
					catch (final Exception exception)
					{
						LOG.error(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()"
								+ Logging.HYPHEN + "Throwable exception occured " + exception.getMessage(), exception);
						sftpFlag = false;
					}
				}
			}
		}

		if (LOG.isDebugEnabled())
		{
			LOG.debug(Jnjb2bCoreConstants.Logging.SFTP_UTIL + Logging.HYPHEN + "uploadMultipleFileToSftp()" + Logging.HYPHEN
					+ Logging.END_OF_METHOD + Logging.HYPHEN + Logging.END_TIME + JnJCommonUtil.getCurrentDateTime());
		}
		return sftpFlag;
	}
	
	
}
