//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:51:39 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_createdelorder_v1.createdeliveredorderswebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for in_orderLines complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="in_orderLines">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaterialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QuantityRequested" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesUOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerLineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Lot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnloadingPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingPoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Plant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Batch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StockPartner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceOverrideAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceOverrideReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriceOverrideApprover" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "in_orderLines", propOrder =
{ "materialNumber", "quantityRequested", "salesUOM", "customerLineNumber", "lot", "route", "unloadingPoint", "shippingPoint",
		"plant", "batch", "stockPartner", "priceOverrideAmount", "priceOverrideReason", "priceOverrideApprover", "freight" ,"itemHold" })
@XmlRootElement(name = "InOrderLines")
public class InOrderLines
{

	@XmlElement(name = "MaterialNumber", required = true, nillable = true)
	protected String materialNumber;
	@XmlElement(name = "QuantityRequested", required = true, nillable = true)
	protected String quantityRequested;
	@XmlElement(name = "SalesUOM", required = true, nillable = true)
	protected String salesUOM;
	@XmlElementRef(name = "CustomerLineNumber", type = JAXBElement.class, required = false)
	protected JAXBElement<String> customerLineNumber;
	@XmlElementRef(name = "Lot", type = JAXBElement.class, required = false)
	protected JAXBElement<String> lot;
	@XmlElementRef(name = "Route", type = JAXBElement.class, required = false)
	protected JAXBElement<String> route;
	@XmlElementRef(name = "UnloadingPoint", type = JAXBElement.class, required = false)
	protected JAXBElement<String> unloadingPoint;
	@XmlElementRef(name = "ShippingPoint", type = JAXBElement.class, required = false)
	protected JAXBElement<String> shippingPoint;
	@XmlElementRef(name = "Plant", type = JAXBElement.class, required = false)
	protected JAXBElement<String> plant;
	@XmlElementRef(name = "Batch", type = JAXBElement.class, required = false)
	protected JAXBElement<String> batch;
	@XmlElementRef(name = "StockPartner", type = JAXBElement.class, required = false)
	protected JAXBElement<String> stockPartner;
	@XmlElementRef(name = "PriceOverrideAmount", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceOverrideAmount;
	@XmlElementRef(name = "PriceOverrideReason", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceOverrideReason;
	@XmlElementRef(name = "PriceOverrideApprover", type = JAXBElement.class, required = false)
	protected JAXBElement<String> priceOverrideApprover;
	@XmlElementRef(name = "Freight", type = JAXBElement.class, required = false)
	protected JAXBElement<String> freight;
	@XmlElementRef(name = "Item_Hold", type = JAXBElement.class, required = false)
    protected JAXBElement<String> itemHold;

	/**
	 * Gets the value of the materialNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaterialNumber()
	{
		return materialNumber;
	}

	/**
	 * Sets the value of the materialNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setMaterialNumber(final String value)
	{
		this.materialNumber = value;
	}

	/**
	 * Gets the value of the quantityRequested property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQuantityRequested()
	{
		return quantityRequested;
	}

	/**
	 * Sets the value of the quantityRequested property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setQuantityRequested(final String value)
	{
		this.quantityRequested = value;
	}

	/**
	 * Gets the value of the salesUOM property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSalesUOM()
	{
		return salesUOM;
	}

	/**
	 * Sets the value of the salesUOM property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setSalesUOM(final String value)
	{
		this.salesUOM = value;
	}

	/**
	 * Gets the value of the customerLineNumber property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getCustomerLineNumber()
	{
		return customerLineNumber;
	}

	/**
	 * Sets the value of the customerLineNumber property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setCustomerLineNumber(final JAXBElement<String> value)
	{
		this.customerLineNumber = value;
	}

	/**
	 * Gets the value of the lot property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getLot()
	{
		return lot;
	}

	/**
	 * Sets the value of the lot property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setLot(final JAXBElement<String> value)
	{
		this.lot = value;
	}

	/**
	 * Gets the value of the route property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getRoute()
	{
		return route;
	}

	/**
	 * Sets the value of the route property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setRoute(final JAXBElement<String> value)
	{
		this.route = value;
	}

	/**
	 * Gets the value of the unloadingPoint property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getUnloadingPoint()
	{
		return unloadingPoint;
	}

	/**
	 * Sets the value of the unloadingPoint property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setUnloadingPoint(final JAXBElement<String> value)
	{
		this.unloadingPoint = value;
	}

	/**
	 * Gets the value of the shippingPoint property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getShippingPoint()
	{
		return shippingPoint;
	}

	/**
	 * Sets the value of the shippingPoint property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setShippingPoint(final JAXBElement<String> value)
	{
		this.shippingPoint = value;
	}

	/**
	 * Gets the value of the plant property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPlant()
	{
		return plant;
	}

	/**
	 * Sets the value of the plant property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPlant(final JAXBElement<String> value)
	{
		this.plant = value;
	}

	/**
	 * Gets the value of the batch property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getBatch()
	{
		return batch;
	}

	/**
	 * Sets the value of the batch property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setBatch(final JAXBElement<String> value)
	{
		this.batch = value;
	}

	/**
	 * Gets the value of the stockPartner property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getStockPartner()
	{
		return stockPartner;
	}

	/**
	 * Sets the value of the stockPartner property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setStockPartner(final JAXBElement<String> value)
	{
		this.stockPartner = value;
	}

	/**
	 * Gets the value of the priceOverrideAmount property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceOverrideAmount()
	{
		return priceOverrideAmount;
	}

	/**
	 * Sets the value of the priceOverrideAmount property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceOverrideAmount(final JAXBElement<String> value)
	{
		this.priceOverrideAmount = value;
	}

	/**
	 * Gets the value of the priceOverrideReason property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceOverrideReason()
	{
		return priceOverrideReason;
	}

	/**
	 * Sets the value of the priceOverrideReason property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceOverrideReason(final JAXBElement<String> value)
	{
		this.priceOverrideReason = value;
	}

	/**
	 * Gets the value of the priceOverrideApprover property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getPriceOverrideApprover()
	{
		return priceOverrideApprover;
	}

	/**
	 * Sets the value of the priceOverrideApprover property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setPriceOverrideApprover(final JAXBElement<String> value)
	{
		this.priceOverrideApprover = value;
	}

	/**
	 * Gets the value of the freight property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getFreight()
	{
		return freight;
	}

	/**
	 * Sets the value of the freight property.
	 * 
	 * @param value
	 *           allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setFreight(final JAXBElement<String> value)
	{
		this.freight = value;
	}

	/**
     * Gets the value of the itemHold property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getItemHold() {
        return itemHold;
    }

    /**
     * Sets the value of the itemHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItemHold(JAXBElement<String> value) {
        this.itemHold = value;
    }

}
