//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:51:39 AM IST 
//


package com.jnj.hcswmd01.mu007_epic_createdelorder_v1.createdeliveredorderswebservice;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jnj.hcswmd01.mu007_epic_createdelorder_v1.createdeliveredorderswebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateDeliveredOrdersOutput_QNAME = new QName("http://hcswmd01.jnj.com/MU007_EPIC_CreateDelOrder_v1/createDeliveredOrdersWebservice", "createDeliveredOrdersOutput");
    private final static QName _CreateDeliveredOrdersInput_QNAME = new QName("http://hcswmd01.jnj.com/MU007_EPIC_CreateDelOrder_v1/createDeliveredOrdersWebservice", "createDeliveredOrdersInput");
    private final static QName _InOrderLinesShippingPoint_QNAME = new QName("", "ShippingPoint");
    private final static QName _InOrderLinesPriceOverrideReason_QNAME = new QName("", "PriceOverrideReason");
    private final static QName _InOrderLinesBatch_QNAME = new QName("", "Batch");
    private final static QName _InOrderLinesPlant_QNAME = new QName("", "Plant");
    private final static QName _InOrderLinesStockPartner_QNAME = new QName("", "StockPartner");
    private final static QName _InOrderLinesFreight_QNAME = new QName("", "Freight");
    private final static QName _InOrderLinesPriceOverrideApprover_QNAME = new QName("", "PriceOverrideApprover");
    private final static QName _InOrderLinesLot_QNAME = new QName("", "Lot");
    private final static QName _InOrderLinesUnloadingPoint_QNAME = new QName("", "UnloadingPoint");
    private final static QName _InOrderLinesRoute_QNAME = new QName("", "Route");
    private final static QName _InOrderLinesCustomerLineNumber_QNAME = new QName("", "CustomerLineNumber");
    private final static QName _InOrderLinesPriceOverrideAmount_QNAME = new QName("", "PriceOverrideAmount");
    private final static QName _InOrderLinesItemHold_QNAME = new QName("", "Item_Hold");
    private final static QName _CreateDeliveredOrdersOutputErrorMessage_QNAME = new QName("", "errorMessage");
    private final static QName _CreateDeliveredOrdersOutputOutOrderReasonCode_QNAME = new QName("", "out_OrderReasonCode");
    private final static QName _CreateDeliveredOrdersOutputOutStockPartnerHdr_QNAME = new QName("", "out_StockPartnerHdr");
    private final static QName _CreateDeliveredOrdersInputInProcedureType_QNAME = new QName("", "in_ProcedureType");
    private final static QName _CreateDeliveredOrdersInputInGatewayRelatedOrdernumber_QNAME = new QName("", "in_GatewayRelatedOrdernumber");
    private final static QName _CreateDeliveredOrdersInputInCreditCardAccountNumber_QNAME = new QName("", "in_CreditCardAccountNumber");
    private final static QName _CreateDeliveredOrdersInputInDealerPONumber_QNAME = new QName("", "in_DealerPONumber");
    private final static QName _CreateDeliveredOrdersInputInCaseNumber_QNAME = new QName("", "in_CaseNumber");
    private final static QName _CreateDeliveredOrdersInputInCAS_QNAME = new QName("", "in_CAS");
    private final static QName _CreateDeliveredOrdersInputInHoldCode_QNAME = new QName("", "in_HoldCode");
    private final static QName _CreateDeliveredOrdersInputInSurgeonID_QNAME = new QName("", "in_SurgeonID");
    private final static QName _CreateDeliveredOrdersInputInEmailAddress_QNAME = new QName("", "in_EmailAddress");
    private final static QName _CreateDeliveredOrdersInputInSurgeonSpecialty_QNAME = new QName("", "in_SurgeonSpecialty");
    private final static QName _CreateDeliveredOrdersInputInStockPartnerHdr_QNAME = new QName("", "in_Stock_Partner_Hdr");
    private final static QName _CreateDeliveredOrdersInputInReferenceOrder_QNAME = new QName("", "in_ReferenceOrder");
    private final static QName _CreateDeliveredOrdersInputInSalesRepUCN_QNAME = new QName("", "in_SalesRepUCN");
    private final static QName _CreateDeliveredOrdersInputInCreditCardExpirationCard_QNAME = new QName("", "in_CreditCardExpirationCard");
    private final static QName _CreateDeliveredOrdersInputInCreditCardType_QNAME = new QName("", "in_CreditCardType");
    private final static QName _CreateDeliveredOrdersInputInZone_QNAME = new QName("", "in_Zone");
    private final static QName _CreateDeliveredOrdersInputInSurgeonName_QNAME = new QName("", "in_SurgeonName");
    private final static QName _CreateDeliveredOrdersInputInInterbody_QNAME = new QName("", "in_Interbody");
    private final static QName _CreateDeliveredOrdersInputInOrderReason_QNAME = new QName("", "in_OrderReason");
    private final static QName _CreateDeliveredOrdersInputInPathology_QNAME = new QName("", "in_Pathology");
    private final static QName _CreateDeliveredOrdersInputInCreditCardSequenceNumber_QNAME = new QName("", "in_CreditCardSequenceNumber");
    private final static QName _CreateDeliveredOrdersInputInBillToNumber_QNAME = new QName("", "in_BillToNumber");
    private final static QName _CreateDeliveredOrdersInputInOrthobiologics_QNAME = new QName("", "in_Orthobiologics");
    private final static QName _CreateDeliveredOrdersInputInLevelsInstrumented_QNAME = new QName("", "in_LevelsInstrumented");
    private final static QName _CreateDeliveredOrdersInputInCustomerNotes_QNAME = new QName("", "in_CustomerNotes");
    private final static QName _CreateDeliveredOrdersInputInRequestedDeliveryDate_QNAME = new QName("", "in_RequestedDeliveryDate");
    private final static QName _CreateDeliveredOrdersInputInSurgicalApproach_QNAME = new QName("", "in_SurgicalApproach");
    private final static QName _CreateDeliveredOrdersInputInCaseDate_QNAME = new QName("", "in_CaseDate");
    private final static QName _CreateDeliveredOrdersInputInLevelsIBFusion_QNAME = new QName("", "in_LevelsIBFusion");
    private final static QName _OutOrderLinesFeeMin_QNAME = new QName("", "FeeMin");
    private final static QName _OutOrderLinesGrossPrice_QNAME = new QName("", "GrossPrice");
    private final static QName _OutOrderLinesHandling_QNAME = new QName("", "Handling");
    private final static QName _OutOrderLinesBillingDeliveryBlock_QNAME = new QName("", "BillingDeliveryBlock");
    private final static QName _OutOrderLinesLineNumber_QNAME = new QName("", "LineNumber");
    private final static QName _OutOrderLinesNetValue_QNAME = new QName("", "NetValue");
    private final static QName _OutOrderLinesMaterialNumber_QNAME = new QName("", "MaterialNumber");
    private final static QName _OutOrderLinesSubstitutionReason_QNAME = new QName("", "SubstitutionReason");
    private final static QName _OutOrderLinesAvailableQuantity_QNAME = new QName("", "AvailableQuantity");
    private final static QName _OutOrderLinesDiscounts_QNAME = new QName("", "Discounts");
    private final static QName _OutOrderLinesMaterialEntered_QNAME = new QName("", "MaterialEntered");
    private final static QName _OutOrderLinesMessage_QNAME = new QName("", "Message");
    private final static QName _OutOrderLinesFee_QNAME = new QName("", "Fee");
    private final static QName _OutOrderLinesTax_QNAME = new QName("", "Tax");
    private final static QName _OutOrderLinesHSAPromotion_QNAME = new QName("", "HSAPromotion");
    private final static QName _OutOrderLinesFreightAndHandling_QNAME = new QName("", "FreightAndHandling");
    private final static QName _OutOrderLinesDropShipFee_QNAME = new QName("", "DropShipFee");
    private final static QName _OutOrderLinesBaseUOM_QNAME = new QName("", "BaseUOM");
    private final static QName _OutOrderLinesPriceType_QNAME = new QName("", "PriceType");
    private final static QName _OutOrderLinesSalesUOM_QNAME = new QName("", "SalesUOM");
    private final static QName _OutOrderLinesItemCategory_QNAME = new QName("", "ItemCategory");
    private final static QName _OutOrderLinesHigherLevelItemNumber_QNAME = new QName("", "HigherLevelItemNumber");
    private final static QName _ScheduledLinesScheduledLineNumber_QNAME = new QName("", "ScheduledLineNumber");
    private final static QName _ScheduledLinesDeliveryDate_QNAME = new QName("", "DeliveryDate");
    private final static QName _ScheduledLinesQuantity_QNAME = new QName("", "quantity");
    private final static QName _ScheduledLinesShipDate_QNAME = new QName("", "ShipDate");
    private final static QName _ScheduledLinesLineStatus_QNAME = new QName("", "LineStatus");
    private final static QName _ScheduledLinesMaterialAvailabilityDate_QNAME = new QName("", "MaterialAvailabilityDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jnj.hcswmd01.mu007_epic_createdelorder_v1.createdeliveredorderswebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateDeliveredOrdersOutput }
     * 
     */
    public CreateDeliveredOrdersOutput createCreateDeliveredOrdersOutput() {
        return new CreateDeliveredOrdersOutput();
    }

    /**
     * Create an instance of {@link CreateDeliveredOrdersInput }
     * 
     */
    public CreateDeliveredOrdersInput createCreateDeliveredOrdersInput() {
        return new CreateDeliveredOrdersInput();
    }

    /**
     * Create an instance of {@link InOrderLines }
     * 
     */
    public InOrderLines createInOrderLines() {
        return new InOrderLines();
    }

    /**
     * Create an instance of {@link OutOrderLines }
     * 
     */
    public OutOrderLines createOutOrderLines() {
        return new OutOrderLines();
    }

    /**
     * Create an instance of {@link ScheduledLines }
     * 
     */
    public ScheduledLines createScheduledLines() {
        return new ScheduledLines();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDeliveredOrdersOutput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_CreateDelOrder_v1/createDeliveredOrdersWebservice", name = "createDeliveredOrdersOutput")
    public JAXBElement<CreateDeliveredOrdersOutput> createCreateDeliveredOrdersOutput(CreateDeliveredOrdersOutput value) {
        return new JAXBElement<CreateDeliveredOrdersOutput>(_CreateDeliveredOrdersOutput_QNAME, CreateDeliveredOrdersOutput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDeliveredOrdersInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_CreateDelOrder_v1/createDeliveredOrdersWebservice", name = "createDeliveredOrdersInput")
    public JAXBElement<CreateDeliveredOrdersInput> createCreateDeliveredOrdersInput(CreateDeliveredOrdersInput value) {
        return new JAXBElement<CreateDeliveredOrdersInput>(_CreateDeliveredOrdersInput_QNAME, CreateDeliveredOrdersInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingPoint", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesShippingPoint(String value) {
        return new JAXBElement<String>(_InOrderLinesShippingPoint_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceOverrideReason", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesPriceOverrideReason(String value) {
        return new JAXBElement<String>(_InOrderLinesPriceOverrideReason_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Batch", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesBatch(String value) {
        return new JAXBElement<String>(_InOrderLinesBatch_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Plant", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesPlant(String value) {
        return new JAXBElement<String>(_InOrderLinesPlant_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StockPartner", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesStockPartner(String value) {
        return new JAXBElement<String>(_InOrderLinesStockPartner_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Freight", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesFreight(String value) {
        return new JAXBElement<String>(_InOrderLinesFreight_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceOverrideApprover", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesPriceOverrideApprover(String value) {
        return new JAXBElement<String>(_InOrderLinesPriceOverrideApprover_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lot", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesLot(String value) {
        return new JAXBElement<String>(_InOrderLinesLot_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnloadingPoint", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesUnloadingPoint(String value) {
        return new JAXBElement<String>(_InOrderLinesUnloadingPoint_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Route", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesRoute(String value) {
        return new JAXBElement<String>(_InOrderLinesRoute_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomerLineNumber", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesCustomerLineNumber(String value) {
        return new JAXBElement<String>(_InOrderLinesCustomerLineNumber_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceOverrideAmount", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesPriceOverrideAmount(String value) {
        return new JAXBElement<String>(_InOrderLinesPriceOverrideAmount_QNAME, String.class, InOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Item_Hold", scope = InOrderLines.class)
    public JAXBElement<String> createInOrderLinesItemHold(String value) {
        return new JAXBElement<String>(_InOrderLinesItemHold_QNAME, String.class, InOrderLines.class, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errorMessage", scope = CreateDeliveredOrdersOutput.class)
    public JAXBElement<String> createCreateDeliveredOrdersOutputErrorMessage(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersOutputErrorMessage_QNAME, String.class, CreateDeliveredOrdersOutput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "out_OrderReasonCode", scope = CreateDeliveredOrdersOutput.class)
    public JAXBElement<String> createCreateDeliveredOrdersOutputOutOrderReasonCode(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersOutputOutOrderReasonCode_QNAME, String.class, CreateDeliveredOrdersOutput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "out_StockPartnerHdr", scope = CreateDeliveredOrdersOutput.class)
    public JAXBElement<String> createCreateDeliveredOrdersOutputOutStockPartnerHdr(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersOutputOutStockPartnerHdr_QNAME, String.class, CreateDeliveredOrdersOutput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_ProcedureType", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInProcedureType(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInProcedureType_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_GatewayRelatedOrdernumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInGatewayRelatedOrdernumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInGatewayRelatedOrdernumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardAccountNumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCreditCardAccountNumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCreditCardAccountNumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_DealerPONumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInDealerPONumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInDealerPONumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CaseNumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCaseNumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCaseNumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CAS", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCAS(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCAS_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_HoldCode", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInHoldCode(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInHoldCode_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_SurgeonID", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInSurgeonID(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInSurgeonID_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_EmailAddress", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInEmailAddress(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInEmailAddress_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_SurgeonSpecialty", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInSurgeonSpecialty(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInSurgeonSpecialty_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_Stock_Partner_Hdr", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInStockPartnerHdr(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInStockPartnerHdr_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_ReferenceOrder", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInReferenceOrder(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInReferenceOrder_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_SalesRepUCN", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInSalesRepUCN(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInSalesRepUCN_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardExpirationCard", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCreditCardExpirationCard(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCreditCardExpirationCard_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardType", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCreditCardType(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCreditCardType_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_Zone", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInZone(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInZone_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_SurgeonName", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInSurgeonName(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInSurgeonName_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_Interbody", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInInterbody(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInInterbody_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_OrderReason", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInOrderReason(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInOrderReason_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_Pathology", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInPathology(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInPathology_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CreditCardSequenceNumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCreditCardSequenceNumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCreditCardSequenceNumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_BillToNumber", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInBillToNumber(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInBillToNumber_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_Orthobiologics", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInOrthobiologics(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInOrthobiologics_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_LevelsInstrumented", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInLevelsInstrumented(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInLevelsInstrumented_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CustomerNotes", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCustomerNotes(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCustomerNotes_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_RequestedDeliveryDate", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInRequestedDeliveryDate(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInRequestedDeliveryDate_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_SurgicalApproach", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInSurgicalApproach(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInSurgicalApproach_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_CaseDate", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInCaseDate(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInCaseDate_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "in_LevelsIBFusion", scope = CreateDeliveredOrdersInput.class)
    public JAXBElement<String> createCreateDeliveredOrdersInputInLevelsIBFusion(String value) {
        return new JAXBElement<String>(_CreateDeliveredOrdersInputInLevelsIBFusion_QNAME, String.class, CreateDeliveredOrdersInput.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FeeMin", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFeeMin(String value) {
        return new JAXBElement<String>(_OutOrderLinesFeeMin_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GrossPrice", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesGrossPrice(String value) {
        return new JAXBElement<String>(_OutOrderLinesGrossPrice_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StockPartner", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesStockPartner(String value) {
        return new JAXBElement<String>(_InOrderLinesStockPartner_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Handling", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHandling(String value) {
        return new JAXBElement<String>(_OutOrderLinesHandling_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lot", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesLot(String value) {
        return new JAXBElement<String>(_InOrderLinesLot_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BillingDeliveryBlock", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesBillingDeliveryBlock(String value) {
        return new JAXBElement<String>(_OutOrderLinesBillingDeliveryBlock_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesLineNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesLineNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetValue", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesNetValue(String value) {
        return new JAXBElement<String>(_OutOrderLinesNetValue_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMaterialNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesMaterialNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubstitutionReason", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesSubstitutionReason(String value) {
        return new JAXBElement<String>(_OutOrderLinesSubstitutionReason_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Route", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesRoute(String value) {
        return new JAXBElement<String>(_InOrderLinesRoute_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AvailableQuantity", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesAvailableQuantity(String value) {
        return new JAXBElement<String>(_OutOrderLinesAvailableQuantity_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Discounts", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesDiscounts(String value) {
        return new JAXBElement<String>(_OutOrderLinesDiscounts_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingPoint", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesShippingPoint(String value) {
        return new JAXBElement<String>(_InOrderLinesShippingPoint_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialEntered", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMaterialEntered(String value) {
        return new JAXBElement<String>(_OutOrderLinesMaterialEntered_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Message", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesMessage(String value) {
        return new JAXBElement<String>(_OutOrderLinesMessage_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Freight", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFreight(String value) {
        return new JAXBElement<String>(_InOrderLinesFreight_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fee", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFee(String value) {
        return new JAXBElement<String>(_OutOrderLinesFee_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tax", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesTax(String value) {
        return new JAXBElement<String>(_OutOrderLinesTax_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HSAPromotion", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHSAPromotion(String value) {
        return new JAXBElement<String>(_OutOrderLinesHSAPromotion_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FreightAndHandling", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesFreightAndHandling(String value) {
        return new JAXBElement<String>(_OutOrderLinesFreightAndHandling_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DropShipFee", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesDropShipFee(String value) {
        return new JAXBElement<String>(_OutOrderLinesDropShipFee_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BaseUOM", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesBaseUOM(String value) {
        return new JAXBElement<String>(_OutOrderLinesBaseUOM_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PriceType", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesPriceType(String value) {
        return new JAXBElement<String>(_OutOrderLinesPriceType_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SalesUOM", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesSalesUOM(String value) {
        return new JAXBElement<String>(_OutOrderLinesSalesUOM_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ItemCategory", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesItemCategory(String value) {
        return new JAXBElement<String>(_OutOrderLinesItemCategory_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HigherLevelItemNumber", scope = OutOrderLines.class)
    public JAXBElement<String> createOutOrderLinesHigherLevelItemNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesHigherLevelItemNumber_QNAME, String.class, OutOrderLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScheduledLineNumber", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesScheduledLineNumber(String value) {
        return new JAXBElement<String>(_ScheduledLinesScheduledLineNumber_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesDeliveryDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesDeliveryDate_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineNumber", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesLineNumber(String value) {
        return new JAXBElement<String>(_OutOrderLinesLineNumber_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesQuantity(String value) {
        return new JAXBElement<String>(_ScheduledLinesQuantity_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesShipDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesShipDate_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineStatus", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesLineStatus(String value) {
        return new JAXBElement<String>(_ScheduledLinesLineStatus_QNAME, String.class, ScheduledLines.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaterialAvailabilityDate", scope = ScheduledLines.class)
    public JAXBElement<String> createScheduledLinesMaterialAvailabilityDate(String value) {
        return new JAXBElement<String>(_ScheduledLinesMaterialAvailabilityDate_QNAME, String.class, ScheduledLines.class, value);
    }

}
