//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 10:51:39 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://hcswmd01.jnj.com/MU007_EPIC_CreateDelOrder_v1/createDeliveredOrdersWebservice")
package com.jnj.hcswmd01.mu007_epic_createdelorder_v1.createdeliveredorderswebservice;
